package test;


import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ONIN
 */
public class ZCustomer_BookingHistory1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ZCustomer_BookingHistory1.class.getName());

    /**
     * Creates new form Reservation_History2
     */
    public ZCustomer_BookingHistory1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser10 = new com.toedter.calendar.JDateChooser();
        jlbl_4 = new javax.swing.JLabel();
        jlbl_1 = new javax.swing.JLabel();
        jlbl_2 = new javax.swing.JLabel();
        jlbl_3 = new javax.swing.JLabel();
        jlbl_8 = new javax.swing.JLabel();
        jlbl_5 = new javax.swing.JLabel();
        jlbl_6 = new javax.swing.JLabel();
        jlbl_7 = new javax.swing.JLabel();
        jlbl_9 = new javax.swing.JLabel();
        jlbl_10 = new javax.swing.JLabel();
        jlbl_11 = new javax.swing.JLabel();
        jtext_1 = new javax.swing.JTextField();
        jtext_5 = new javax.swing.JTextField();
        jtext_3 = new javax.swing.JTextField();
        jtext_9 = new javax.swing.JTextField();
        jtext_2 = new javax.swing.JTextField();
        jdate_11 = new com.toedter.calendar.JDateChooser();
        jdate_4 = new com.toedter.calendar.JDateChooser();
        jcb_8 = new javax.swing.JComboBox<>();
        jcb_6 = new javax.swing.JComboBox<>();
        jcb_10 = new javax.swing.JComboBox<>();
        jcb_7 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jbtnDelete = new javax.swing.JButton();
        jbtn_insert = new javax.swing.JButton();
        jbtn_Reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_1 = new javax.swing.JTable();
        jbtn_exit = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jbtn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 77, 94));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_4.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_4.setText("Date");
        getContentPane().add(jlbl_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jlbl_1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_1.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_1.setText("Reservation ID");
        getContentPane().add(jlbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jlbl_2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_2.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_2.setText("Customer Name");
        getContentPane().add(jlbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jlbl_3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_3.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_3.setText("Contact Number");
        getContentPane().add(jlbl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jlbl_8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_8.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_8.setText("Table #");
        getContentPane().add(jlbl_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jlbl_5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_5.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_5.setText("Time");
        getContentPane().add(jlbl_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jlbl_6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_6.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_6.setText("Session");
        getContentPane().add(jlbl_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jlbl_7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_7.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_7.setText("Pax");
        getContentPane().add(jlbl_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jlbl_9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_9.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_9.setText("Total Bill");
        getContentPane().add(jlbl_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 30));

        jlbl_10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_10.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_10.setText("Status");
        getContentPane().add(jlbl_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jlbl_11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlbl_11.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_11.setText("Date Booked");
        getContentPane().add(jlbl_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, 20));

        jtext_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jtext_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, -1));

        jtext_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jtext_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 170, -1));

        jtext_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jtext_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 170, -1));

        jtext_9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jtext_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 170, -1));

        jtext_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jtext_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, -1));
        getContentPane().add(jdate_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 170, -1));
        getContentPane().add(jdate_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, -1));

        jcb_8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jcb_8.addActionListener(this::jcb_8ActionPerformed);
        getContentPane().add(jcb_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 170, -1));

        jcb_6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Lunch", "Dinner" }));
        jcb_6.addActionListener(this::jcb_6ActionPerformed);
        getContentPane().add(jcb_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 170, -1));

        jcb_10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Completed", "Pending" }));
        jcb_10.addActionListener(this::jcb_10ActionPerformed);
        getContentPane().add(jcb_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 170, 20));

        jcb_7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jcb_7.addActionListener(this::jcb_7ActionPerformed);
        getContentPane().add(jcb_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 170, -1));

        jPanel3.setBackground(new java.awt.Color(57, 77, 94));

        jbtnDelete.setBackground(new java.awt.Color(255, 0, 0));
        jbtnDelete.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(this::jbtnDeleteActionPerformed);

        jbtn_insert.setBackground(new java.awt.Color(102, 255, 0));
        jbtn_insert.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jbtn_insert.setText("Insert");
        jbtn_insert.addActionListener(this::jbtn_insertActionPerformed);

        jbtn_Reset.setBackground(new java.awt.Color(255, 0, 0));
        jbtn_Reset.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jbtn_Reset.setText("Reset");
        jbtn_Reset.addActionListener(this::jbtn_ResetActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jbtn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jbtnDelete)
                .addGap(18, 18, 18)
                .addComponent(jbtn_insert)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(474, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDelete)
                    .addComponent(jbtn_insert)
                    .addComponent(jbtn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 370, 520));

        jTable_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CDA 122", "Ana Hawkins",  new Integer(989876), "March 28, 2026", "12:00 PM", "Lunch",  new Integer(3),  new Integer(3), "Php 3,800", "Completed", "March 11, 2026"},
                {"DAS 223", "Rayn Cruz",  new Integer(928288), "February 14, 2026", "1 PM", "Lunch",  new Integer(2),  new Integer(1), "Php 2,500", "Completed", "February"},
                {"RES001", "Maria Santos",  new Integer(934943), "Nov 18, 2025", "6:30 PM", "Dinner",  new Integer(3),  new Integer(4), "Php 4,400", "Completed", "Nov 10, 2025"},
                {"RES002", "John Reyes",  new Integer(9432993), "Jan 9, 2026", "1:00 PM", "Lunch",  new Integer(6),  new Integer(3), "Php 6,000", "Completed", "Jan 2, 2026"},
                {"RES003", "Angela Cruz",  new Integer(32400349), "Oct 27, 2025", "7:00 PM", "Dinner",  new Integer(3),  new Integer(2), "Php 3,400", "Completed", "Oct 20, 2025"},
                {"RES004", "Carlo Mendoza",  new Integer(433920), "Feb 14, 2026", "12:30 PM", "Lunch",  new Integer(2),  new Integer(1), "Php 2,300", "Completed", "Feb 8, 2026"},
                {"RES005", "Sofia Villanueva",  new Integer(433243), "Aug 6, 2025", "6:00 PM", "Dinner",  new Integer(1),  new Integer(7), "Php 1,100", "Completed", "Jul 30, 2025"},
                {"RES006", "Mark Bautista",  new Integer(5454543), "Mar 3, 2026", "1:30 PM", "Lunch",  new Integer(3),  new Integer(11), "Php 4,500", "Completed", "Feb 25, 2026"},
                {"RES007", "Diana Flores",  new Integer(6654465), "Dec 21, 2025", "7:30 PM", "Dinner",  new Integer(6),  new Integer(2), "Php 10,400", "Completed", "Dec 14, 2025"},
                {"RES008", "Kevin Ramos",  new Integer(56454544), "Sep 15, 2025", "6:45 PM", "Dinner",  new Integer(9),  new Integer(15), "Php 15,900", "Completed", "Sep 7, 2025"},
                {"RES009", "Patricia Gomez",  new Integer(234325), "Apr 5, 2026", "1:00 PM", "Lunch",  new Integer(5),  new Integer(6), "Php 7,500", "Completed", "Mar 29, 2026"},
                {"RES010", "Daniel Navarro",  new Integer(764767), "Jul 19, 2025", "1:00 PM", "Lunch",  new Integer(3),  new Integer(18), "Php 3,400", "Completed", "Jul 10, 2025"},
                {"RES011", "Roger Fernandez",  new Integer(53543), "May 11, 2026", "7:30 PM", "Dinner",  new Integer(4),  new Integer(4), "Php 5,300", "Completed", "May 3, 2026"}
            },
            new String [] {
                "Reservation ID", "Customer Name", "Contact", "Date", "Time", "Session", "Pax", "Table #", "Total Bill", "Status", "Date Booked"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_1);
        if (jTable_1.getColumnModel().getColumnCount() > 0) {
            jTable_1.getColumnModel().getColumn(0).setResizable(false);
            jTable_1.getColumnModel().getColumn(1).setResizable(false);
            jTable_1.getColumnModel().getColumn(2).setResizable(false);
            jTable_1.getColumnModel().getColumn(3).setResizable(false);
            jTable_1.getColumnModel().getColumn(4).setResizable(false);
            jTable_1.getColumnModel().getColumn(5).setResizable(false);
            jTable_1.getColumnModel().getColumn(6).setResizable(false);
            jTable_1.getColumnModel().getColumn(7).setResizable(false);
            jTable_1.getColumnModel().getColumn(8).setResizable(false);
            jTable_1.getColumnModel().getColumn(9).setResizable(false);
            jTable_1.getColumnModel().getColumn(10).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 577, 450));

        jbtn_exit.setBackground(new java.awt.Color(204, 204, 255));
        jbtn_exit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jbtn_exit.setText("X");
        jbtn_exit.addActionListener(this::jbtn_exitActionPerformed);
        getContentPane().add(jbtn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 40, 20));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 216, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(57, 77, 94));
        jLabel9.setText("Search by Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 130, 30));

        jbtn_search.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_search.setText("Search");
        jbtn_search.addActionListener(this::jbtn_searchActionPerformed);
        getContentPane().add(jbtn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_8ActionPerformed

    private void jcb_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_6ActionPerformed

    private void jcb_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_10ActionPerformed

    private void jcb_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_7ActionPerformed
private JFrame frame;
    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel model= (DefaultTableModel) jTable_1.getModel();
        if (jTable_1.getSelectedRow() == -1){
            if (jTable_1.getRowCount() == 0){
            
                JOptionPane.showMessageDialog(null, "No data to delete ","Reservation History System",
                JOptionPane.OK_OPTION) ;
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Select a row to delete ", "Reservation History System", 
                JOptionPane.OK_OPTION) ;
                
            }
        }else{
            model.removeRow(jTable_1.getSelectedRow());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_insertActionPerformed
        DefaultTableModel model= (DefaultTableModel) jTable_1.getModel();
        model.addRow(new Object[]{
        jtext_1.getText(),
        jtext_2.getText(),
        jtext_3.getText(),
        jdate_4.getDate(),
        jtext_5.getText(),
        jcb_6.getSelectedIndex(),
        jcb_7.getSelectedIndex(),
        jcb_8.getSelectedIndex(),
        jtext_9.getText(),
        jcb_10.getSelectedIndex(),
        jdate_11.getDate(),    
        });
    }//GEN-LAST:event_jbtn_insertActionPerformed

    private void jbtn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ResetActionPerformed
        
        
        jtext_1.setText(null);
        jtext_2.setText(null);
        jtext_3.setText(null);
        jdate_4.setDate(null);
        jtext_5.setText(null);
        jcb_6.setSelectedIndex(0);
        jcb_7.setSelectedIndex(0);
        jcb_8.setSelectedIndex(0);
        jtext_9.setText(null);
        jcb_10.setSelectedIndex(0);
        jdate_11.setDate(null);
    }//GEN-LAST:event_jbtn_ResetActionPerformed

    private void jbtn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_exitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Reservation History System",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_jbtn_exitActionPerformed

    private void jbtn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_searchActionPerformed
       if (jDateChooser1.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Please select a date");
        return;
    }

    // Match the format used in the JTable
    SimpleDateFormat sDate = new SimpleDateFormat("MMM d, yyyy");
    String date = sDate.format(jDateChooser1.getDate());

    DefaultTableModel model = (DefaultTableModel) jTable_1.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    jTable_1.setRowSorter(sorter);

    // Filter ONLY Date Booked column
    sorter.setRowFilter(RowFilter.regexFilter("^" + date + "$", 10));
    }//GEN-LAST:event_jbtn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ZCustomer_BookingHistory1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtn_Reset;
    private javax.swing.JButton jbtn_exit;
    private javax.swing.JButton jbtn_insert;
    private javax.swing.JButton jbtn_search;
    private javax.swing.JComboBox<String> jcb_10;
    private javax.swing.JComboBox<String> jcb_6;
    private javax.swing.JComboBox<String> jcb_7;
    private javax.swing.JComboBox<String> jcb_8;
    private com.toedter.calendar.JDateChooser jdate_11;
    private com.toedter.calendar.JDateChooser jdate_4;
    private javax.swing.JLabel jlbl_1;
    private javax.swing.JLabel jlbl_10;
    private javax.swing.JLabel jlbl_11;
    private javax.swing.JLabel jlbl_2;
    private javax.swing.JLabel jlbl_3;
    private javax.swing.JLabel jlbl_4;
    private javax.swing.JLabel jlbl_5;
    private javax.swing.JLabel jlbl_6;
    private javax.swing.JLabel jlbl_7;
    private javax.swing.JLabel jlbl_8;
    private javax.swing.JLabel jlbl_9;
    private javax.swing.JTextField jtext_1;
    private javax.swing.JTextField jtext_2;
    private javax.swing.JTextField jtext_3;
    private javax.swing.JTextField jtext_5;
    private javax.swing.JTextField jtext_9;
    // End of variables declaration//GEN-END:variables
}
