/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author lotte
 */
public class Conformation_Method extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Conformation_Method.class.getName());

    /**
     * Creates new form Conformation_Method
     */
    public Conformation_Method() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_confirmation = new javax.swing.JButton();
        confirmation_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_confirmation.setBackground(new java.awt.Color(23, 57, 86));
        Btn_confirmation.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Btn_confirmation.setForeground(new java.awt.Color(255, 255, 255));
        Btn_confirmation.setText("Confirm");
        Btn_confirmation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Btn_confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 100, 40));

        confirmation_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/confirmation.png"))); // NOI18N
        getContentPane().add(confirmation_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Conformation_Method().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_confirmation;
    private javax.swing.JLabel confirmation_bg;
    // End of variables declaration//GEN-END:variables
}
