/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author kyshgel
 */
public class Customer_Homepage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer_Homepage.class.getName());

    /**
     * Creates new form draft
     */
    public Customer_Homepage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dc_date = new com.toedter.calendar.JDateChooser();
        cb_branch = new javax.swing.JComboBox<>();
        sp_guest = new javax.swing.JSpinner();
        cb_time = new javax.swing.JComboBox<>();
        btn_bookNow = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        logo_homepage = new javax.swing.JLabel();
        btn_profile = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        btn_dc = new javax.swing.JButton();
        btn_abt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_rsv = new javax.swing.JButton();
        bg_homepage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 580));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dc_date.setMaxSelectableDate(new java.util.Date(1798650075000L));
        dc_date.setMinSelectableDate(new java.util.Date(1772298075000L));
        jPanel1.add(dc_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 100, 30));

        cb_branch.setBackground(new java.awt.Color(57, 77, 94));
        cb_branch.setForeground(new java.awt.Color(255, 255, 255));
        cb_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SM North Edsa", "SM Megamall" }));
        jPanel1.add(cb_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 120, 30));

        sp_guest.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        jPanel1.add(sp_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 70, 30));

        cb_time.setBackground(new java.awt.Color(57, 77, 94));
        cb_time.setForeground(new java.awt.Color(255, 255, 255));
        cb_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunch", "Dinner" }));
        cb_time.addActionListener(this::cb_timeActionPerformed);
        jPanel1.add(cb_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 70, 30));

        btn_bookNow.setBackground(new java.awt.Color(153, 0, 0));
        btn_bookNow.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btn_bookNow.setForeground(new java.awt.Color(255, 255, 255));
        btn_bookNow.setText("Book Now");
        btn_bookNow.setBorder(null);
        btn_bookNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_bookNow.setFocusPainted(false);
        btn_bookNow.setFocusable(false);
        btn_bookNow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_bookNow.addActionListener(this::btn_bookNowActionPerformed);
        jPanel1.add(btn_bookNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 90, 30));

        jPanel3.setBackground(new java.awt.Color(57, 77, 94));
        jPanel3.setMaximumSize(new java.awt.Dimension(158, 580));
        jPanel3.setMinimumSize(new java.awt.Dimension(158, 580));
        jPanel3.setPreferredSize(new java.awt.Dimension(158, 580));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_homepage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imresizer-invertedlogo.png"))); // NOI18N
        jPanel3.add(logo_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 110));

        btn_profile.setBackground(new java.awt.Color(57, 77, 94));
        btn_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_profile.setText("    PROFILE");
        btn_profile.setBorder(null);
        btn_profile.setContentAreaFilled(false);
        btn_profile.setFocusPainted(false);
        btn_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_profileMouseExited(evt);
            }
        });
        btn_profile.addActionListener(this::btn_profileActionPerformed);
        jPanel3.add(btn_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 90, 30));

        btn_menu.setBackground(new java.awt.Color(57, 77, 94));
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText(" MENU & SPECIALS");
        btn_menu.setBorder(null);
        btn_menu.setContentAreaFilled(false);
        btn_menu.setFocusPainted(false);
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuMouseExited(evt);
            }
        });
        btn_menu.addActionListener(this::btn_menuActionPerformed);
        jPanel3.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 20));

        btn_dc.setBackground(new java.awt.Color(57, 77, 94));
        btn_dc.setForeground(new java.awt.Color(255, 255, 255));
        btn_dc.setText("DINE CLUB");
        btn_dc.setBorder(null);
        btn_dc.setContentAreaFilled(false);
        btn_dc.setFocusPainted(false);
        btn_dc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dcMouseExited(evt);
            }
        });
        btn_dc.addActionListener(this::btn_dcActionPerformed);
        jPanel3.add(btn_dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 20));

        btn_abt.setBackground(new java.awt.Color(57, 77, 94));
        btn_abt.setForeground(new java.awt.Color(255, 255, 255));
        btn_abt.setText("   ABOUT US");
        btn_abt.setBorder(null);
        btn_abt.setContentAreaFilled(false);
        btn_abt.setFocusPainted(false);
        btn_abt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_abtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_abtMouseExited(evt);
            }
        });
        btn_abt.addActionListener(this::btn_abtActionPerformed);
        jPanel3.add(btn_abt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 100, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("All Rights Reserved.");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 130, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("© 2026 The House of 7 Buffet.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 180, 30));

        btn_rsv.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btn_rsv.setForeground(new java.awt.Color(55, 77, 94));
        btn_rsv.setText("RESERVATIONS");
        btn_rsv.setBorder(null);
        btn_rsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_rsvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_rsvMouseExited(evt);
            }
        });
        jPanel3.add(btn_rsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 284, 120, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 158, -1));

        bg_homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bg10.png"))); // NOI18N
        bg_homepage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bg_homepage.setMaximumSize(new java.awt.Dimension(760, 580));
        bg_homepage.setMinimumSize(new java.awt.Dimension(760, 580));
        bg_homepage.setPreferredSize(new java.awt.Dimension(760, 580));
        bg_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_homepageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_homepageMouseExited(evt);
            }
        });
        jPanel1.add(bg_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 750, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bg_homepageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_homepageMouseEntered
        btn_bookNow.setBackground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_bg_homepageMouseEntered

    private void bg_homepageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_homepageMouseExited
    btn_bookNow.setBackground(new java.awt.Color(172, 0, 0));
    }//GEN-LAST:event_bg_homepageMouseExited

    private void cb_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_timeActionPerformed

    private void btn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseEntered
    btn_menu.setForeground(new Color(255,200,120));   
    btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_btn_menuMouseEntered

    private void btn_dcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dcMouseEntered
    btn_dc.setForeground(new Color(255,200,120));
    btn_dc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_btn_dcMouseEntered

    private void btn_abtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_abtMouseEntered
    btn_abt.setForeground(new Color(255,200,120)); 
    btn_abt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_btn_abtMouseEntered

    private void btn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseExited
    btn_menu.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menuMouseExited

    private void btn_dcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dcMouseExited
    btn_dc.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dcMouseExited

    private void btn_abtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_abtMouseExited
    btn_abt.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_abtMouseExited

    private void btn_abtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_abtActionPerformed

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseExited
        btn_profile.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_profileMouseExited

    private void btn_profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseEntered
        btn_profile.setForeground(new Color(255,200,120));
        btn_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_profileMouseEntered

    private void btn_dcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dcActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_bookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookNowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bookNowActionPerformed

    private void btn_rsvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rsvMouseEntered
    btn_rsv.setBackground(new java.awt.Color(110,135,154));
    btn_rsv.setForeground(Color.WHITE);
    btn_rsv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_rsvMouseEntered

    private void btn_rsvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rsvMouseExited
    btn_rsv.setBackground(Color.WHITE);
    btn_rsv.setForeground(new java.awt.Color(55,77,94));
    }//GEN-LAST:event_btn_rsvMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer_Homepage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_homepage;
    private javax.swing.JButton btn_abt;
    private javax.swing.JButton btn_bookNow;
    private javax.swing.JButton btn_dc;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_profile;
    private javax.swing.JButton btn_rsv;
    private javax.swing.JComboBox<String> cb_branch;
    private javax.swing.JComboBox<String> cb_time;
    private com.toedter.calendar.JDateChooser dc_date;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo_homepage;
    private javax.swing.JSpinner sp_guest;
    // End of variables declaration//GEN-END:variables
}
