/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;
import javax.swing.SpinnerNumberModel;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author lotte
 */
public class Customer_BookingWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer_BookingWindow.class.getName());

    public Customer_BookingWindow(java.util.Date passedDate, int passedPax, String passedTime) {
        initComponents();
        setLocationRelativeTo(null);
        
        dp_date.setDate(passedDate);
        
        SpinnerNumberModel model = new SpinnerNumberModel(passedPax, 1, 50, 1);
        spn_pax.setModel(model);
        
        cb_time.setSelectedItem(passedTime.toUpperCase());

        cb_time.addActionListener(evt -> updateSeatAvailability());
        dp_date.getDateEditor().addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) updateSeatAvailability();
        });
        spn_pax.addChangeListener(evt -> updateSeatAvailability());

        loadUserData();
        updateSeatAvailability();
    }
    
    private void updateSeatAvailability() {
        Date utilDate = dp_date.getDate();

        if (utilDate == null) {
            btn_topay.setEnabled(false);
        } else {
            btn_topay.setEnabled(true);
        }
    }
    
    private void loadUserData() {
        if (UserSession.loggedInEmail != null && !UserSession.loggedInEmail.isEmpty()) {
            
            txt_email.setText(UserSession.loggedInEmail);
            
            txt_email.setEditable(false);
            txt_FName.setEditable(false);
            txt_LName.setEditable(false);
            txt_num.setEditable(false);

            Connect db = new Connect();
            db.DoConnect();

            if (db.con != null) {
                String query = "SELECT F_NAME, L_NAME, CP_NUM FROM DBHOUSE.VIPACCOUNTS WHERE EMAIL = ?";
                
                try (Connection con = db.con;
                     PreparedStatement pst = con.prepareStatement(query)) {
                     
                    pst.setString(1, UserSession.loggedInEmail);
                    
                    try (ResultSet rs = pst.executeQuery()) {
                        if (rs.next()) {
                            txt_FName.setText(rs.getString("F_NAME"));
                            txt_LName.setText(rs.getString("L_NAME"));
                            txt_num.setText(rs.getString("CP_NUM"));
                        }
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Failed to load user account details: " + ex.getMessage());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_time = new javax.swing.JComboBox<>();
        txt_LName = new javax.swing.JTextField();
        dp_date = new com.toedter.calendar.JDateChooser();
        txt_email = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        spn_pax = new javax.swing.JSpinner();
        btn_topay = new javax.swing.JButton();
        txt_FName = new javax.swing.JTextField();
        btn_backhomepage = new javax.swing.JButton();
        booking_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_time.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cb_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LUNCH", "DINNER" }));
        cb_time.addActionListener(this::cb_timeActionPerformed);
        getContentPane().add(cb_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, 30));
        getContentPane().add(txt_LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, 30));
        getContentPane().add(dp_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 120, 30));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 230, 30));
        getContentPane().add(txt_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 230, 30));

        spn_pax.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(spn_pax, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 80, 30));

        btn_topay.setBackground(new java.awt.Color(57, 77, 94));
        btn_topay.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_topay.setText("Proceed to Payment");
        btn_topay.setBorder(null);
        btn_topay.addActionListener(this::btn_topayActionPerformed);
        getContentPane().add(btn_topay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 170, 30));

        txt_FName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(txt_FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 160, 30));

        btn_backhomepage.setBackground(new java.awt.Color(255, 255, 255));
        btn_backhomepage.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_backhomepage.setForeground(new java.awt.Color(23, 57, 86));
        btn_backhomepage.setText("<");
        btn_backhomepage.setBorderPainted(false);
        btn_backhomepage.addActionListener(this::btn_backhomepageActionPerformed);
        getContentPane().add(btn_backhomepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        booking_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BOOKING.png"))); // NOI18N
        getContentPane().add(booking_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_timeActionPerformed
        String selectedBranch = cb_time.getSelectedItem().toString();

    if (selectedBranch.equals("LUNCH")) {
        System.out.println("LUNCH");
    }

    if (selectedBranch.equals("DINNER")) {
        System.out.println("DINNER");
    }// TODO add your handling code here:
    }//GEN-LAST:event_cb_timeActionPerformed

    private void btn_topayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_topayActionPerformed
        try {
            String firstName = txt_FName.getText().trim();
            String lastName = txt_LName.getText().trim();
            String email = txt_email.getText().trim();
            String phone = txt_num.getText().trim();
            int pax = (Integer) spn_pax.getValue();
            String mealType = cb_time.getSelectedItem().toString();
            Date utilDate = dp_date.getDate();

            if (firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || phone.isEmpty() || utilDate == null) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields!");
                return;
            }

            if (!Booking_DBConnection.isValidEmail(email)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid email address!");
                return;
            }

            if (!Booking_DBConnection.isValidPhone(phone)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid phone number!");
                return;
            }

            Customer_BookingPayment paymentWindow = new Customer_BookingPayment(this, firstName, lastName, email, phone, utilDate, mealType, pax);
            paymentWindow.setVisible(true);
            this.setVisible(false); // hide this window

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_topayActionPerformed

    private void btn_backhomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backhomepageActionPerformed
        
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel your reservation?", "Cancel Reservation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (choice == JOptionPane.YES_OPTION) {
            new Customer_Homepage().setVisible(true);
            this.dispose(); 
        } 
    }//GEN-LAST:event_btn_backhomepageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel booking_bg;
    private javax.swing.JButton btn_backhomepage;
    private javax.swing.JButton btn_topay;
    private javax.swing.JComboBox<String> cb_time;
    private com.toedter.calendar.JDateChooser dp_date;
    private javax.swing.JSpinner spn_pax;
    private javax.swing.JTextField txt_FName;
    private javax.swing.JTextField txt_LName;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_num;
    // End of variables declaration//GEN-END:variables
}
