/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author lotte
 */
public class Customer_BookingWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer_BookingWindow.class.getName());

    /**
     * Creates new form Booking_Window
     */
    public Customer_BookingWindow() {
        initComponents();
        setLocationRelativeTo(null);
        
        SpinnerNumberModel model = new SpinnerNumberModel(1, 1, 50, 1);
        spn_pax.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_branch = new javax.swing.JComboBox<>();
        cb_time = new javax.swing.JComboBox<>();
        dp_date = new com.toedter.calendar.JDateChooser();
        txt_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        spn_pax = new javax.swing.JSpinner();
        txt_promo = new javax.swing.JTextField();
        btn_topay = new javax.swing.JButton();
        booking_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_branch.setFont(new java.awt.Font("Century Gothic", 0, 8)); // NOI18N
        cb_branch.setMaximumRowCount(2);
        cb_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SM NORTH EDSA", "SM MEGAMALL" }));
        cb_branch.addActionListener(this::cb_branchActionPerformed);
        getContentPane().add(cb_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, 30));

        cb_time.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cb_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LUNCH", "DINNER" }));
        cb_time.addActionListener(this::cb_timeActionPerformed);
        getContentPane().add(cb_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, 30));

        dp_date.setDateFormatString("MM-dd-yy");
        getContentPane().add(dp_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 110, 30));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 230, 30));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 230, 30));
        getContentPane().add(txt_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 230, 30));

        spn_pax.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(spn_pax, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 80, 30));
        getContentPane().add(txt_promo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 110, 30));

        btn_topay.setBackground(new java.awt.Color(185, 153, 79));
        btn_topay.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_topay.setText("Proceed to Payment");
        btn_topay.addActionListener(this::btn_topayActionPerformed);
        getContentPane().add(btn_topay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 160, -1));

        booking_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/BOOKING1.png"))); // NOI18N
        getContentPane().add(booking_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_branchActionPerformed
    String selectedBranch = cb_branch.getSelectedItem().toString();
        if (selectedBranch.equals("SM NORTH EDSA")) {
        System.out.println("SM NORTH EDSA");
        }
        if (selectedBranch.equals("SM MEGAMALL")) {
        System.out.println("SM MEGAMALL"); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_cb_branchActionPerformed

    private void cb_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_timeActionPerformed
        String selectedBranch = cb_time.getSelectedItem().toString();

    if (selectedBranch.equals("LUNCH")) {
        System.out.println("LUNCH");
    }

    if (selectedBranch.equals("DINNER")) {
        System.out.println("DINNER");
    }// TODO add your handling code here:
    }//GEN-LAST:event_cb_timeActionPerformed

    private void btn_topayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_topayActionPerformed
        new Customer_BookingPayment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_topayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer_BookingWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel booking_bg;
    private javax.swing.JButton btn_topay;
    private javax.swing.JComboBox<String> cb_branch;
    private javax.swing.JComboBox<String> cb_time;
    private com.toedter.calendar.JDateChooser dp_date;
    private javax.swing.JSpinner spn_pax;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_num;
    private javax.swing.JTextField txt_promo;
    // End of variables declaration//GEN-END:variables
}
