/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.Timer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ska
 */
public class Customer_Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer_Login.class.getName());

    
    public Customer_Login() {
        initComponents();
        
        this.setResizable(true);
        getContentPane().setPreferredSize(new java.awt.Dimension(900, 580));
        pack();
        this.setResizable(false);
        
        getContentPane().setComponentZOrder(imagePanelwelcome1, 0);
        setLocationRelativeTo(null);
        
        makeFlatButton(btn_login);
        makeFlatButton(btn_createSignup);
        dc_createBday.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanelwelcome1 = new img.ImagePanelwelcome();
        btn_emplogin1 = new javax.swing.JLabel();
        chk_loginShowPass = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txt_loginEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_loginSignup = new javax.swing.JLabel();
        txt_loginPass = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        imagePanelcreate = new img.ImagePanelcreate();
        jLabel10 = new javax.swing.JLabel();
        txt_createFirstName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_createSignup = new javax.swing.JButton();
        btn_lcreateLogin = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_createEmail = new javax.swing.JTextField();
        txt_createLastName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_createNumber = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cb_createGender = new javax.swing.JComboBox<>();
        txt_createPass1 = new javax.swing.JPasswordField();
        dc_createBday = new com.toedter.calendar.JDateChooser();
        chk_createShowPass = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The House Of 7");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 580));
        getContentPane().setLayout(null);

        btn_emplogin1.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        btn_emplogin1.setForeground(new java.awt.Color(153, 153, 153));
        btn_emplogin1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_emplogin1.setText("Employee Log-in");
        btn_emplogin1.setToolTipText("");
        btn_emplogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_emplogin1MouseClicked(evt);
            }
        });

        chk_loginShowPass.addActionListener(this::chk_loginShowPassActionPerformed);

        jLabel4.setBackground(new java.awt.Color(47, 74, 91));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 74, 91));
        jLabel4.setText("E-mail:");
        jLabel4.setToolTipText("");

        txt_loginEmail.setBackground(new java.awt.Color(229, 229, 229));
        txt_loginEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_loginEmail.setForeground(new java.awt.Color(47, 74, 91));
        txt_loginEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txt_loginEmail.addActionListener(this::txt_loginEmailActionPerformed);

        jLabel5.setBackground(new java.awt.Color(47, 74, 91));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(47, 74, 91));
        jLabel5.setText("Password:");
        jLabel5.setToolTipText("");

        btn_login.setBackground(new java.awt.Color(47, 74, 91));
        btn_login.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(238, 238, 238));
        btn_login.setText("LOG-IN");
        btn_login.setMaximumSize(new java.awt.Dimension(293, 26));
        btn_login.setMinimumSize(new java.awt.Dimension(293, 26));
        btn_login.addActionListener(this::btn_loginActionPerformed);

        jLabel7.setBackground(new java.awt.Color(47, 74, 91));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(47, 74, 91));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("No account yet? ");
        jLabel7.setToolTipText("");

        btn_loginSignup.setBackground(new java.awt.Color(47, 74, 91));
        btn_loginSignup.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        btn_loginSignup.setForeground(new java.awt.Color(47, 74, 91));
        btn_loginSignup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_loginSignup.setText("Sign-up");
        btn_loginSignup.setToolTipText("");
        btn_loginSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginSignupMouseClicked(evt);
            }
        });

        txt_loginPass.setBackground(new java.awt.Color(229, 229, 229));
        txt_loginPass.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_loginPass.setForeground(new java.awt.Color(47, 74, 91));
        txt_loginPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 5, 10));
        txt_loginPass.addActionListener(this::txt_loginPassActionPerformed);

        jLabel19.setBackground(new java.awt.Color(47, 74, 91));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(47, 74, 91));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Show Password");
        jLabel19.setToolTipText("");

        javax.swing.GroupLayout imagePanelwelcome1Layout = new javax.swing.GroupLayout(imagePanelwelcome1);
        imagePanelwelcome1.setLayout(imagePanelwelcome1Layout);
        imagePanelwelcome1Layout.setHorizontalGroup(
            imagePanelwelcome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelwelcome1Layout.createSequentialGroup()
                .addGroup(imagePanelwelcome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanelwelcome1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(imagePanelwelcome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(imagePanelwelcome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(txt_loginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(imagePanelwelcome1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_loginShowPass))
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(imagePanelwelcome1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_emplogin1))
                    .addGroup(imagePanelwelcome1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_loginSignup)))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        imagePanelwelcome1Layout.setVerticalGroup(
            imagePanelwelcome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelwelcome1Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_loginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanelwelcome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_loginShowPass)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(imagePanelwelcome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btn_loginSignup))
                .addGap(92, 92, 92)
                .addComponent(btn_emplogin1)
                .addGap(14, 14, 14))
        );

        getContentPane().add(imagePanelwelcome1);
        imagePanelwelcome1.setBounds(0, 0, 900, 580);

        jLabel10.setBackground(new java.awt.Color(47, 74, 91));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(47, 74, 91));
        jLabel10.setText("E-mail:");
        jLabel10.setToolTipText("");

        txt_createFirstName.setBackground(new java.awt.Color(229, 229, 229));
        txt_createFirstName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_createFirstName.setForeground(new java.awt.Color(47, 74, 91));
        txt_createFirstName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txt_createFirstName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_createFirstName.addActionListener(this::txt_createFirstNameActionPerformed);

        jLabel11.setBackground(new java.awt.Color(47, 74, 91));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(47, 74, 91));
        jLabel11.setText("Password:");
        jLabel11.setToolTipText("");

        btn_createSignup.setBackground(new java.awt.Color(47, 74, 91));
        btn_createSignup.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_createSignup.setForeground(new java.awt.Color(238, 238, 238));
        btn_createSignup.setText("SIGN UP");
        btn_createSignup.setMaximumSize(new java.awt.Dimension(293, 26));
        btn_createSignup.setMinimumSize(new java.awt.Dimension(293, 26));
        btn_createSignup.addActionListener(this::btn_createSignupActionPerformed);

        btn_lcreateLogin.setBackground(new java.awt.Color(47, 74, 91));
        btn_lcreateLogin.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        btn_lcreateLogin.setForeground(new java.awt.Color(47, 74, 91));
        btn_lcreateLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_lcreateLogin.setText("< Back  to Log In");
        btn_lcreateLogin.setToolTipText("");
        btn_lcreateLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lcreateLoginMouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(47, 74, 91));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(47, 74, 91));
        jLabel13.setText("First Name:");
        jLabel13.setToolTipText("");

        txt_createEmail.setBackground(new java.awt.Color(229, 229, 229));
        txt_createEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_createEmail.setForeground(new java.awt.Color(47, 74, 91));
        txt_createEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txt_createEmail.addActionListener(this::txt_createEmailActionPerformed);

        txt_createLastName.setBackground(new java.awt.Color(229, 229, 229));
        txt_createLastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_createLastName.setForeground(new java.awt.Color(47, 74, 91));
        txt_createLastName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txt_createLastName.addActionListener(this::txt_createLastNameActionPerformed);

        jLabel14.setBackground(new java.awt.Color(47, 74, 91));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(47, 74, 91));
        jLabel14.setText("Last Name:");
        jLabel14.setToolTipText("");

        jLabel15.setBackground(new java.awt.Color(47, 74, 91));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(47, 74, 91));
        jLabel15.setText("Mobile Number (+63):");
        jLabel15.setToolTipText("");

        txt_createNumber.setBackground(new java.awt.Color(229, 229, 229));
        txt_createNumber.setBorder(null);
        txt_createNumber.setForeground(new java.awt.Color(47, 74, 91));
        try {
            txt_createNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("  ###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_createNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_createNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_createNumber.setMargin(new java.awt.Insets(2, 12, 2, 12));

        jLabel16.setBackground(new java.awt.Color(47, 74, 91));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(47, 74, 91));
        jLabel16.setText("Gender:");
        jLabel16.setToolTipText("");

        jLabel17.setBackground(new java.awt.Color(47, 74, 91));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(47, 74, 91));
        jLabel17.setText("Birthday:");
        jLabel17.setToolTipText("");

        cb_createGender.setBackground(new java.awt.Color(229, 229, 229));
        cb_createGender.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cb_createGender.setForeground(new java.awt.Color(47, 74, 91));
        cb_createGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        cb_createGender.setBorder(null);
        cb_createGender.setPreferredSize(new java.awt.Dimension(72, 30));
        cb_createGender.addActionListener(this::cb_createGenderActionPerformed);

        txt_createPass1.setBackground(new java.awt.Color(229, 229, 229));
        txt_createPass1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_createPass1.setForeground(new java.awt.Color(47, 74, 91));
        txt_createPass1.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 5, 10));
        txt_createPass1.setCaretColor(new java.awt.Color(47, 74, 91));
        txt_createPass1.addActionListener(this::txt_createPass1ActionPerformed);

        dc_createBday.setBackground(new java.awt.Color(229, 229, 229));
        dc_createBday.setForeground(new java.awt.Color(47, 74, 91));
        dc_createBday.setDateFormatString("MM-dd-yy");
        dc_createBday.setEnabled(false);
        dc_createBday.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dc_createBday.setMaxSelectableDate(new java.util.Date(1777482082000L));
        dc_createBday.setMinSelectableDate(new java.util.Date(-2209013918000L));

        chk_createShowPass.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        chk_createShowPass.setForeground(new java.awt.Color(47, 74, 91));
        chk_createShowPass.setBorder(null);
        chk_createShowPass.addActionListener(this::chk_createShowPassActionPerformed);

        jLabel18.setBackground(new java.awt.Color(47, 74, 91));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(47, 74, 91));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Show Password");
        jLabel18.setToolTipText("");

        javax.swing.GroupLayout imagePanelcreateLayout = new javax.swing.GroupLayout(imagePanelcreate);
        imagePanelcreate.setLayout(imagePanelcreateLayout);
        imagePanelcreateLayout.setHorizontalGroup(
            imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelcreateLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_createFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, imagePanelcreateLayout.createSequentialGroup()
                            .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(cb_createGender, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dc_createBday, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(txt_createPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(imagePanelcreateLayout.createSequentialGroup()
                            .addComponent(btn_lcreateLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_createSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(imagePanelcreateLayout.createSequentialGroup()
                            .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15)
                                .addComponent(txt_createNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_createEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(imagePanelcreateLayout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(txt_createLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(imagePanelcreateLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk_createShowPass))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        imagePanelcreateLayout.setVerticalGroup(
            imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelcreateLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelcreateLayout.createSequentialGroup()
                        .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(3, 3, 3)
                        .addComponent(txt_createFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_createLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(imagePanelcreateLayout.createSequentialGroup()
                        .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_createEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_createNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11))
                .addGap(2, 2, 2)
                .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_createPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_createGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc_createBday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(chk_createShowPass))
                .addGap(25, 25, 25)
                .addGroup(imagePanelcreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_lcreateLogin)
                    .addComponent(btn_createSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        getContentPane().add(imagePanelcreate);
        imagePanelcreate.setBounds(-5, -1, 910, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_createShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_createShowPassActionPerformed
        if (chk_createShowPass.isSelected()) {
            txt_createPass1.setEchoChar((char)0);
        } else {
            txt_createPass1.setEchoChar('*');
        }
    }//GEN-LAST:event_chk_createShowPassActionPerformed

    private void txt_createPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_createPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_createPass1ActionPerformed

    private void cb_createGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_createGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_createGenderActionPerformed

    private void txt_createLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_createLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_createLastNameActionPerformed

    private void txt_createEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_createEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_createEmailActionPerformed

    private void btn_lcreateLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lcreateLoginMouseClicked
        slideToLogin();
    }//GEN-LAST:event_btn_lcreateLoginMouseClicked

    private void btn_createSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createSignupActionPerformed
        String fName = txt_createFirstName.getText();
        String lName = txt_createLastName.getText();
        String gender = cb_createGender.getSelectedItem().toString();
        String pass = new String(txt_createPass1.getPassword());
        java.util.Date bdayInput = dc_createBday.getDate();
        String email = txt_createEmail.getText();
        String phone = txt_createNumber.getText().trim();

        if (fName.isEmpty() || email.isEmpty() || pass.isEmpty() || bdayInput == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }
        Connect db = new Connect();
        db.DoConnect();

        if (db.con != null) {
            try (Connection con = db.con) {

                String checkEmailSql = "SELECT EMAIL FROM DBHOUSE.VIPACCOUNTS WHERE EMAIL = ?";
                try (PreparedStatement checkEmailPst = con.prepareStatement(checkEmailSql)) {
                    checkEmailPst.setString(1, email);
                    try (ResultSet rs = checkEmailPst.executeQuery()) {
                        if (rs.next()) {
                            JOptionPane.showMessageDialog(this,
                                "The email " + email + " is already registered to another account.",
                                "Duplicate Email", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    }
                }

                String checkPhoneSql = "SELECT CP_NUM FROM DBHOUSE.VIPACCOUNTS WHERE CP_NUM = ?";
                try (PreparedStatement checkPhonePst = con.prepareStatement(checkPhoneSql)) {
                    checkPhonePst.setString(1, phone);
                    try (ResultSet rs = checkPhonePst.executeQuery()) {
                        if (rs.next()) {
                            JOptionPane.showMessageDialog(this,
                                "The mobile number " + phone + " is already registered to another account.",
                                "Duplicate Number", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    }
                }
                String newVipId = getNextVipId();
                java.sql.Date dateReg = new java.sql.Date(System.currentTimeMillis());

                String insertSql = "INSERT INTO DBHOUSE.VIPACCOUNTS (VIP_ID, DATE_REG, F_NAME, L_NAME, GENDER, BDAY, CP_NUM, EMAIL, PASS) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

                try (PreparedStatement pst = con.prepareStatement(insertSql)) {
                    pst.setString(1, newVipId);
                    pst.setDate(2, dateReg);
                    pst.setString(3, fName);
                    pst.setString(4, lName);
                    pst.setString(5, gender);
                    pst.setDate(6, new java.sql.Date(bdayInput.getTime()));
                    pst.setString(7, phone);
                    pst.setString(8, email);
                    pst.setString(9, pass);

                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Registration Successful. Please Log in.", "Registration Successful", JOptionPane.PLAIN_MESSAGE);

                    slideToLogin();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "DB Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_createSignupActionPerformed

    private void txt_createFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_createFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_createFirstNameActionPerformed

    private void txt_loginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginPassActionPerformed

    private void btn_emplogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_emplogin1MouseClicked
        new Employee_Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_emplogin1MouseClicked

    private void btn_loginSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginSignupMouseClicked
        slideToCreate();
    }//GEN-LAST:event_btn_loginSignupMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String email = txt_loginEmail.getText();
        String password = new String(txt_loginPass.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter A Valid Email and Password!");
            return;
        }

        Connect db = new Connect();
        db.DoConnect();

        if (db.con != null) {
            try (Connection con = db.con;
                PreparedStatement pst = con.prepareStatement("SELECT * FROM DBHOUSE.VIPACCOUNTS WHERE EMAIL = ? AND PASS = ?")) {

                pst.setString(1, email);
                pst.setString(2, password);

                try (ResultSet rs = pst.executeQuery()) {
                    if (rs.next()) {
                        UserSession.loggedInEmail = txt_loginEmail.getText();
                        new Customer_Homepage().setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid credentials.");
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "DB Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_loginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginEmailActionPerformed

    private void chk_loginShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_loginShowPassActionPerformed
        if (chk_loginShowPass.isSelected()) {
            txt_loginPass.setEchoChar((char)0);
        } else {
            txt_loginPass.setEchoChar('*');
        }
    }//GEN-LAST:event_chk_loginShowPassActionPerformed
    
    //BUTTON DESIGNER
    private void makeFlatButton(javax.swing.JButton btn) {
        btn.setFocusPainted(false);
        btn.setBorder(null);
        btn.setContentAreaFilled(false);
        btn.setOpaque(true);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
    
    private void slideToCreate() {
        //CREATE PANEL TO FRONT
        getContentPane().setComponentZOrder(imagePanelcreate, 0); 

        // ANIMATION
        Timer timer = new Timer(10, null);

        timer.addActionListener(new java.awt.event.ActionListener() {
            double y = 580; 

            public void actionPerformed(java.awt.event.ActionEvent e) {
                y += (0 - y) * 0.1;
                imagePanelcreate.setLocation(0, (int)y);
                getContentPane().repaint();

                if (Math.abs(y) < 1) { 
                    imagePanelcreate.setLocation(0, 0);
                    timer.stop();
                }
            }
        });

        timer.start();

        btn_login.setEnabled(false);
        dc_createBday.setVisible(true);
        dc_createBday.setEnabled(true);
    }
    
    private void slideToLogin() {
        // ANIMATION
        Timer timer = new Timer(10, null);

        timer.addActionListener(new java.awt.event.ActionListener() {
            double y = 0;

            public void actionPerformed(java.awt.event.ActionEvent e) {
                y += (580 - y) * 0.1; 

                imagePanelcreate.setLocation(0, (int)y);
                getContentPane().repaint();

                if (Math.abs(580 - y) < 1) { 
                    imagePanelcreate.setLocation(0, 580);
                    timer.stop();
                   
                    getContentPane().setComponentZOrder(imagePanelwelcome1, 0);
                }
            }
        });

        timer.start();
        btn_login.setEnabled(true);
        dc_createBday.setEnabled(false);
    }
    
    private String getNextVipId() {
        int nextNumber = 1000; 

        Connect db = new Connect();
        db.DoConnect();

        if (db.con != null) {
            try (Connection con = db.con;
                 PreparedStatement pst = con.prepareStatement("SELECT MAX(CAST(SUBSTR(VIP_ID, 4) AS INT)) FROM DBHOUSE.VIPACCOUNTS");
                 ResultSet rs = pst.executeQuery()) {

                if (rs.next()) {
                    int maxId = rs.getInt(1);
                    if (maxId > 0) {
                        nextNumber = maxId + 1;
                    }
                }
            } catch (SQLException e) {
                System.out.println("ID Generation Note: " + e.getMessage());
            }
        }
        return "VIP" + nextNumber; 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            org.apache.derby.drda.NetworkServerControl server = 
                new org.apache.derby.drda.NetworkServerControl(java.net.InetAddress.getByName("localhost"), 1527);
            server.start(null);
            System.out.println("Derby Database Server started automatically!");
        } catch (Exception e) {
            System.out.println("Server might already be running, or failed to start: " + e.getMessage());
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer_Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createSignup;
    private javax.swing.JLabel btn_emplogin1;
    private javax.swing.JLabel btn_lcreateLogin;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel btn_loginSignup;
    private javax.swing.JComboBox<String> cb_createGender;
    private javax.swing.JCheckBox chk_createShowPass;
    private javax.swing.JCheckBox chk_loginShowPass;
    private com.toedter.calendar.JDateChooser dc_createBday;
    private img.ImagePanelcreate imagePanelcreate;
    private img.ImagePanelwelcome imagePanelwelcome1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_createEmail;
    private javax.swing.JTextField txt_createFirstName;
    private javax.swing.JTextField txt_createLastName;
    private javax.swing.JFormattedTextField txt_createNumber;
    private javax.swing.JPasswordField txt_createPass1;
    private javax.swing.JTextField txt_loginEmail;
    private javax.swing.JPasswordField txt_loginPass;
    // End of variables declaration//GEN-END:variables
}
