/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author kyshgel
 */
public class Customer_Homepage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer_Homepage.class.getName());

    /**
     * Creates new form draft
     */
    public Customer_Homepage() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        makeFlatButton(btn_bookNow);
        makeFlatButton(btn_navReservations);
        makeFlatButton(btn_navLogout);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dc_date = new com.toedter.calendar.JDateChooser();
        sp_guest = new javax.swing.JSpinner();
        cb_time = new javax.swing.JComboBox<>();
        btn_bookNow = new javax.swing.JButton();
        bg_homepage = new javax.swing.JLabel();
        pnl_nav1 = new javax.swing.JPanel();
        Aboutus_Label4 = new javax.swing.JLabel();
        Aboutus_label5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_navAbout = new javax.swing.JButton();
        btn_navHome = new javax.swing.JButton();
        btn_navMenu = new javax.swing.JButton();
        btn_navDine = new javax.swing.JButton();
        btn_navReservations = new javax.swing.JButton();
        btn_navLogout = new javax.swing.JButton();
        btn_navProf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 580));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dc_date.setBackground(new java.awt.Color(255, 255, 255));
        dc_date.setDateFormatString("MM-dd-yy");
        jPanel1.add(dc_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 140, 30));

        sp_guest.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        sp_guest.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jPanel1.add(sp_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 90, 30));

        cb_time.setBackground(new java.awt.Color(255, 255, 255));
        cb_time.setForeground(new java.awt.Color(255, 255, 255));
        cb_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunch", "Dinner" }));
        cb_time.addActionListener(this::cb_timeActionPerformed);
        jPanel1.add(cb_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 100, 30));

        btn_bookNow.setBackground(new java.awt.Color(153, 0, 0));
        btn_bookNow.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_bookNow.setForeground(new java.awt.Color(255, 255, 255));
        btn_bookNow.setText("Book Now");
        btn_bookNow.setBorder(null);
        btn_bookNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_bookNow.setFocusPainted(false);
        btn_bookNow.setFocusable(false);
        btn_bookNow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_bookNow.addActionListener(this::btn_bookNowActionPerformed);
        jPanel1.add(btn_bookNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 100, 30));

        bg_homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgRevised.png"))); // NOI18N
        bg_homepage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bg_homepage.setMaximumSize(new java.awt.Dimension(760, 580));
        bg_homepage.setMinimumSize(new java.awt.Dimension(760, 580));
        bg_homepage.setPreferredSize(new java.awt.Dimension(760, 580));
        bg_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_homepageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_homepageMouseExited(evt);
            }
        });
        jPanel1.add(bg_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 740, 580));

        pnl_nav1.setBackground(new java.awt.Color(57, 77, 94));
        pnl_nav1.setMaximumSize(new java.awt.Dimension(158, 580));
        pnl_nav1.setMinimumSize(new java.awt.Dimension(158, 580));
        pnl_nav1.setPreferredSize(new java.awt.Dimension(158, 580));
        pnl_nav1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aboutus_Label4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        Aboutus_Label4.setForeground(new java.awt.Color(153, 153, 153));
        Aboutus_Label4.setText("© 2026 The House Of 7 Buffet.");
        pnl_nav1.add(Aboutus_Label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        Aboutus_label5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        Aboutus_label5.setForeground(new java.awt.Color(153, 153, 153));
        Aboutus_label5.setText("All Rights Reserved.");
        pnl_nav1.add(Aboutus_label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        pnl_nav1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 80));

        btn_navAbout.setBackground(new java.awt.Color(55, 77, 94));
        btn_navAbout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navAbout.setForeground(new java.awt.Color(255, 255, 255));
        btn_navAbout.setText("About Us");
        btn_navAbout.setBorder(null);
        btn_navAbout.setContentAreaFilled(false);
        btn_navAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navAbout.setFocusPainted(false);
        btn_navAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navAboutMouseExited(evt);
            }
        });
        btn_navAbout.addActionListener(this::btn_navAboutActionPerformed);
        pnl_nav1.add(btn_navAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 30));

        btn_navHome.setBackground(new java.awt.Color(55, 77, 94));
        btn_navHome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navHome.setForeground(new java.awt.Color(255, 255, 255));
        btn_navHome.setText("Home");
        btn_navHome.setBorder(null);
        btn_navHome.setContentAreaFilled(false);
        btn_navHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navHome.setFocusPainted(false);
        btn_navHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navHomeMouseExited(evt);
            }
        });
        btn_navHome.addActionListener(this::btn_navHomeActionPerformed);
        pnl_nav1.add(btn_navHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        btn_navMenu.setBackground(new java.awt.Color(55, 77, 94));
        btn_navMenu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navMenu.setForeground(new java.awt.Color(255, 255, 255));
        btn_navMenu.setText("Menu & Specials");
        btn_navMenu.setBorder(null);
        btn_navMenu.setContentAreaFilled(false);
        btn_navMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navMenu.setFocusPainted(false);
        btn_navMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navMenuMouseExited(evt);
            }
        });
        btn_navMenu.addActionListener(this::btn_navMenuActionPerformed);
        pnl_nav1.add(btn_navMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 30));

        btn_navDine.setBackground(new java.awt.Color(55, 77, 94));
        btn_navDine.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navDine.setForeground(new java.awt.Color(255, 255, 255));
        btn_navDine.setText("Dine Club");
        btn_navDine.setBorder(null);
        btn_navDine.setContentAreaFilled(false);
        btn_navDine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navDine.setFocusPainted(false);
        btn_navDine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navDineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navDineMouseExited(evt);
            }
        });
        btn_navDine.addActionListener(this::btn_navDineActionPerformed);
        pnl_nav1.add(btn_navDine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        btn_navReservations.setBackground(new java.awt.Color(185, 153, 79));
        btn_navReservations.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_navReservations.setForeground(new java.awt.Color(55, 91, 115));
        btn_navReservations.setText("MY RESERVATIONS");
        btn_navReservations.setBorder(null);
        btn_navReservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navReservations.addActionListener(this::btn_navReservationsActionPerformed);
        pnl_nav1.add(btn_navReservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 30));

        btn_navLogout.setBackground(new java.awt.Color(153, 0, 0));
        btn_navLogout.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_navLogout.setForeground(new java.awt.Color(206, 206, 206));
        btn_navLogout.setText("LOG OUT");
        btn_navLogout.setBorder(null);
        btn_navLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navLogout.addActionListener(this::btn_navLogoutActionPerformed);
        pnl_nav1.add(btn_navLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 80, 30));

        btn_navProf.setBackground(new java.awt.Color(55, 77, 94));
        btn_navProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navProf.setForeground(new java.awt.Color(255, 255, 255));
        btn_navProf.setText("Profile");
        btn_navProf.setBorder(null);
        btn_navProf.setContentAreaFilled(false);
        btn_navProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navProf.setFocusPainted(false);
        btn_navProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navProfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navProfMouseExited(evt);
            }
        });
        btn_navProf.addActionListener(this::btn_navProfActionPerformed);
        pnl_nav1.add(btn_navProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));

        jPanel1.add(pnl_nav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bg_homepageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_homepageMouseEntered
        btn_bookNow.setBackground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_bg_homepageMouseEntered

    private void bg_homepageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_homepageMouseExited
    btn_bookNow.setBackground(new java.awt.Color(172, 0, 0));
    }//GEN-LAST:event_bg_homepageMouseExited

    private void cb_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_timeActionPerformed

    private void btn_bookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookNowActionPerformed
      
        java.util.Date selectedDate = dc_date.getDate();
        int pax = (Integer) sp_guest.getValue();
        String mealTime = cb_time.getSelectedItem().toString();

        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a date first.");
            return;
        }

        new Customer_BookingWindow(selectedDate, pax, mealTime).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_bookNowActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_today1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today1MouseEntered

    private void btn_today1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today1MouseExited

    private void btn_today1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today1ActionPerformed

    private void btn_today2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today2MouseEntered

    private void btn_today2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today2MouseExited

    private void btn_today2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today2ActionPerformed

    private void btn_today3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today3MouseEntered

    private void btn_today3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today3MouseExited

    private void btn_today3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today3ActionPerformed

    private void btn_today4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today4MouseEntered

    private void btn_today4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today4MouseExited

    private void btn_today4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today4ActionPerformed

    private void btn_navAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navAboutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navAboutMouseEntered

    private void btn_navAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navAboutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navAboutMouseExited

    private void btn_navAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navAboutActionPerformed
        new Customer_About_Us().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navAboutActionPerformed

    private void btn_navHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navHomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navHomeMouseEntered

    private void btn_navHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navHomeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navHomeMouseExited

    private void btn_navHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navHomeActionPerformed
        new Customer_Homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navHomeActionPerformed

    private void btn_navMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navMenuMouseEntered

    private void btn_navMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navMenuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navMenuMouseExited

    private void btn_navMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navMenuActionPerformed

    private void btn_navDineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navDineMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navDineMouseEntered

    private void btn_navDineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navDineMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navDineMouseExited

    private void btn_navDineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navDineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navDineActionPerformed

    private void btn_navReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navReservationsActionPerformed
        new Customer_BookingHistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navReservationsActionPerformed

    private void btn_navLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navLogoutActionPerformed

        int choice = JOptionPane.showConfirmDialog(null, "Log out of your account?", "Confirm Log Out", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            UserSession.loggedInEmail = null;
            new Customer_Login().setVisible(true);
            this.dispose();

        } else if (choice == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_btn_navLogoutActionPerformed

    private void btn_navProfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navProfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navProfMouseEntered

    private void btn_navProfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navProfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_navProfMouseExited

    private void btn_navProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navProfActionPerformed
        new Customer_AcctProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navProfActionPerformed

    private void makeFlatButton(javax.swing.JButton btn) {
        btn.setFocusPainted(false);
        btn.setBorder(null);
        btn.setContentAreaFilled(false);
        btn.setOpaque(true);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer_Homepage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutus_Label4;
    private javax.swing.JLabel Aboutus_label5;
    private javax.swing.JLabel bg_homepage;
    private javax.swing.JButton btn_bookNow;
    private javax.swing.JButton btn_navAbout;
    private javax.swing.JButton btn_navDine;
    private javax.swing.JButton btn_navHome;
    private javax.swing.JButton btn_navLogout;
    private javax.swing.JButton btn_navMenu;
    private javax.swing.JButton btn_navProf;
    private javax.swing.JButton btn_navReservations;
    private javax.swing.JComboBox<String> cb_time;
    private com.toedter.calendar.JDateChooser dc_date;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_nav1;
    private javax.swing.JSpinner sp_guest;
    // End of variables declaration//GEN-END:variables
}
