/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import img.MenuItemPanel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author caloy
 */
public class Customer_Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer_Menu.class.getName());

    /**
     */
    public Customer_Menu() {
        initComponents();
        this.setResizable(true);
        
        getContentPane().setPreferredSize(new java.awt.Dimension(900, 580));
        pack();
        this.setResizable(false);
        setLocationRelativeTo(null);
        
        makeFlatButton(btn_navReservations2);
        makeFlatButton(btn_navLogout2);
        pnl_innerMenu.setLayout(new WrapLayout(java.awt.FlowLayout.CENTER, 15, 15));
        
        pnl_menuContainer.getVerticalScrollBar().setUnitIncrement(16);
        
        fetchAndDisplayMenu("Asian");
    }
    
    private void makeFlatButton(javax.swing.JButton btn) {
        btn.setFocusPainted(false);
        btn.setBorder(null);
        btn.setContentAreaFilled(false);
        btn.setOpaque(true);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_nav3 = new javax.swing.JPanel();
        Aboutus_Label6 = new javax.swing.JLabel();
        Aboutus_label7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_navAbout2 = new javax.swing.JButton();
        btn_navHome2 = new javax.swing.JButton();
        btn_navMenu2 = new javax.swing.JButton();
        btn_navDine2 = new javax.swing.JButton();
        btn_navReservations2 = new javax.swing.JButton();
        btn_navLogout2 = new javax.swing.JButton();
        btn_navProf2 = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        pnl_menuContainer = new javax.swing.JScrollPane();
        pnl_innerMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnl_nav3.setBackground(new java.awt.Color(57, 77, 94));
        pnl_nav3.setMaximumSize(new java.awt.Dimension(158, 580));
        pnl_nav3.setMinimumSize(new java.awt.Dimension(158, 580));
        pnl_nav3.setPreferredSize(new java.awt.Dimension(158, 580));
        pnl_nav3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aboutus_Label6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        Aboutus_Label6.setForeground(new java.awt.Color(153, 153, 153));
        Aboutus_Label6.setText("© 2026 The House Of 7 Buffet.");
        pnl_nav3.add(Aboutus_Label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        Aboutus_label7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        Aboutus_label7.setForeground(new java.awt.Color(153, 153, 153));
        Aboutus_label7.setText("All Rights Reserved.");
        pnl_nav3.add(Aboutus_label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        pnl_nav3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 80));

        btn_navAbout2.setBackground(new java.awt.Color(55, 77, 94));
        btn_navAbout2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navAbout2.setForeground(new java.awt.Color(255, 255, 255));
        btn_navAbout2.setText("About Us");
        btn_navAbout2.setBorder(null);
        btn_navAbout2.setContentAreaFilled(false);
        btn_navAbout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navAbout2.setFocusPainted(false);
        btn_navAbout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navAbout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navAbout2MouseExited(evt);
            }
        });
        btn_navAbout2.addActionListener(this::btn_navAbout2ActionPerformed);
        pnl_nav3.add(btn_navAbout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 30));

        btn_navHome2.setBackground(new java.awt.Color(55, 77, 94));
        btn_navHome2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navHome2.setForeground(new java.awt.Color(255, 255, 255));
        btn_navHome2.setText("Home");
        btn_navHome2.setBorder(null);
        btn_navHome2.setContentAreaFilled(false);
        btn_navHome2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navHome2.setFocusPainted(false);
        btn_navHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navHome2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navHome2MouseExited(evt);
            }
        });
        btn_navHome2.addActionListener(this::btn_navHome2ActionPerformed);
        pnl_nav3.add(btn_navHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        btn_navMenu2.setBackground(new java.awt.Color(55, 77, 94));
        btn_navMenu2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btn_navMenu2.setText("Menu & Specials");
        btn_navMenu2.setBorder(null);
        btn_navMenu2.setContentAreaFilled(false);
        btn_navMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navMenu2.setFocusPainted(false);
        btn_navMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navMenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navMenu2MouseExited(evt);
            }
        });
        btn_navMenu2.addActionListener(this::btn_navMenu2ActionPerformed);
        pnl_nav3.add(btn_navMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 30));

        btn_navDine2.setBackground(new java.awt.Color(55, 77, 94));
        btn_navDine2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navDine2.setForeground(new java.awt.Color(255, 255, 255));
        btn_navDine2.setText("Dine Club");
        btn_navDine2.setBorder(null);
        btn_navDine2.setContentAreaFilled(false);
        btn_navDine2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navDine2.setFocusPainted(false);
        btn_navDine2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navDine2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navDine2MouseExited(evt);
            }
        });
        btn_navDine2.addActionListener(this::btn_navDine2ActionPerformed);
        pnl_nav3.add(btn_navDine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        btn_navReservations2.setBackground(new java.awt.Color(185, 153, 79));
        btn_navReservations2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_navReservations2.setForeground(new java.awt.Color(55, 91, 115));
        btn_navReservations2.setText("MY RESERVATIONS");
        btn_navReservations2.setBorder(null);
        btn_navReservations2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navReservations2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navReservations2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navReservations2MouseExited(evt);
            }
        });
        btn_navReservations2.addActionListener(this::btn_navReservations2ActionPerformed);
        pnl_nav3.add(btn_navReservations2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 30));

        btn_navLogout2.setBackground(new java.awt.Color(153, 0, 0));
        btn_navLogout2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_navLogout2.setForeground(new java.awt.Color(206, 206, 206));
        btn_navLogout2.setText("LOG OUT");
        btn_navLogout2.setBorder(null);
        btn_navLogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navLogout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navLogout2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navLogout2MouseExited(evt);
            }
        });
        btn_navLogout2.addActionListener(this::btn_navLogout2ActionPerformed);
        pnl_nav3.add(btn_navLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 80, 30));

        btn_navProf2.setBackground(new java.awt.Color(55, 77, 94));
        btn_navProf2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_navProf2.setForeground(new java.awt.Color(255, 255, 255));
        btn_navProf2.setText("Profile");
        btn_navProf2.setBorder(null);
        btn_navProf2.setContentAreaFilled(false);
        btn_navProf2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_navProf2.setFocusPainted(false);
        btn_navProf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_navProf2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_navProf2MouseExited(evt);
            }
        });
        btn_navProf2.addActionListener(this::btn_navProf2ActionPerformed);
        pnl_nav3.add(btn_navProf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));

        pnlMain.setBackground(new java.awt.Color(88, 119, 144));
        pnlMain.setName(""); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ASIAN");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EUROPEAN");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LATINA");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("WESTERN");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GRILLED");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SALADS");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DESSERT");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnl_header.setBackground(new java.awt.Color(55, 91, 115));
        pnl_header.setMaximumSize(new java.awt.Dimension(681, 115));
        pnl_header.setPreferredSize(new java.awt.Dimension(681, 115));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENUS & SPECIALS");

        lbl_username.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnl_headerLayout = new javax.swing.GroupLayout(pnl_header);
        pnl_header.setLayout(pnl_headerLayout);
        pnl_headerLayout.setHorizontalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnl_headerLayout.setVerticalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_headerLayout.createSequentialGroup()
                        .addComponent(lbl_username)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_headerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52))))
        );

        pnl_menuContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnl_menuContainer.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnl_menuContainer.setViewportView(pnl_innerMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_menuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_header, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnl_nav3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 742, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_header, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_menuContainer)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnl_nav3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
            fetchAndDisplayMenu("Asian");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
            fetchAndDisplayMenu("European");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
     fetchAndDisplayMenu("Latina");
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
      fetchAndDisplayMenu("Western");
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       fetchAndDisplayMenu("Grilled");
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
      fetchAndDisplayMenu("Salads");
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        fetchAndDisplayMenu("Dessert");
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(Color.YELLOW);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(Color.YELLOW);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(Color.YELLOW);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setForeground(Color.YELLOW);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        jLabel10.setForeground(Color.YELLOW);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        jLabel11.setForeground(Color.YELLOW);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jLabel11.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        jLabel12.setForeground(Color.YELLOW);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        jLabel12.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel12MouseExited
/*
    private void btn_navAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navAboutMouseEntered
        if (!btn_navAbout.getForeground().equals(new Color(255, 200, 120))) {
            btn_navAbout.setForeground(new Color(255, 200, 120));
        }
        btn_navAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navAboutMouseEntered

    private void btn_navAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navAboutMouseExited

        btn_navAbout.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_navAboutMouseExited

    private void btn_navAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navAboutActionPerformed
        new Customer_About_Us().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navAboutActionPerformed

    private void btn_navHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navHomeMouseEntered
        if (!btn_navHome.getForeground().equals(new Color(255, 200, 120))) {
            btn_navHome.setForeground(new Color(255, 200, 120));
        }
        btn_navHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navHomeMouseEntered

    private void btn_navHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navHomeMouseExited
        btn_navHome.setForeground(Color.WHITE);

    }//GEN-LAST:event_btn_navHomeMouseExited

    private void btn_navHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navHomeActionPerformed
        new Customer_Homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navHomeActionPerformed

    private void btn_navMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navMenuMouseEntered
        if (!btn_navMenu.getForeground().equals(new Color(255, 200, 120))) {
            btn_navMenu.setForeground(new Color(255, 200, 120));
        }
        btn_navMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navMenuMouseEntered

    private void btn_navMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navMenuMouseExited
        btn_navMenu.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_navMenuMouseExited

    private void btn_navMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navMenuActionPerformed
        new Customer_Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navMenuActionPerformed

    private void btn_navDineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navDineMouseEntered
        if (!btn_navDine.getForeground().equals(new Color(255, 200, 120))) {
            btn_navDine.setForeground(new Color(255, 200, 120));
        }
        btn_navDine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navDineMouseEntered

    private void btn_navDineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navDineMouseExited
        btn_navDine.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_navDineMouseExited

    private void btn_navDineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navDineActionPerformed
        new Customer_DineClub().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navDineActionPerformed

    private void btn_navReservationsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navReservationsMouseEntered
        if (!btn_navReservations.getBackground().equals(new Color(217,180,95))) {
            btn_navReservations.setBackground(new Color(217,180,95));
        }
        btn_navReservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navReservationsMouseEntered

    private void btn_navReservationsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navReservationsMouseExited
        btn_navReservations.setBackground(new Color(185,153,79));
    }//GEN-LAST:event_btn_navReservationsMouseExited

    private void btn_navReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navReservationsActionPerformed
        new Customer_BookingHistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navReservationsActionPerformed

    private void btn_navLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navLogoutMouseEntered
        if (!btn_navLogout.getBackground().equals(new Color(183,14,14))) {
            btn_navLogout.setBackground(new Color(183,14,14));
        }
        btn_navLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navLogoutMouseEntered

    private void btn_navLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navLogoutMouseExited
        btn_navLogout.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btn_navLogoutMouseExited

    private void btn_navLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navLogoutActionPerformed

        int choice = JOptionPane.showConfirmDialog(null, "Log out of your account?", "Confirm Log Out", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            UserSession.loggedInEmail = null;
            new Customer_Login().setVisible(true);
            this.dispose();

        } else if (choice == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_btn_navLogoutActionPerformed

    private void btn_navProfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navProfMouseEntered
        if (!btn_navProf.getForeground().equals(new Color(255, 200, 120))) {
            btn_navProf.setForeground(new Color(255, 200, 120));
        }
        btn_navProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navProfMouseEntered

    private void btn_navProfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navProfMouseExited
        btn_navProf.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_navProfMouseExited

    private void btn_navProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navProfActionPerformed
        new Customer_AcctProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navProfActionPerformed
*/
    private void btn_navAbout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navAbout2MouseEntered
        if (!btn_navAbout2.getForeground().equals(new Color(255, 200, 120))) {
            btn_navAbout2.setForeground(new Color(255, 200, 120));
        }
        btn_navAbout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navAbout2MouseEntered

    private void btn_navAbout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navAbout2MouseExited

        btn_navAbout2.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_navAbout2MouseExited

    private void btn_navAbout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navAbout2ActionPerformed
        new Customer_About_Us().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navAbout2ActionPerformed

    private void btn_navHome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navHome2MouseEntered
        if (!btn_navHome2.getForeground().equals(new Color(255, 200, 120))) {
            btn_navHome2.setForeground(new Color(255, 200, 120));
        }
        btn_navHome2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navHome2MouseEntered

    private void btn_navHome2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navHome2MouseExited
        btn_navHome2.setForeground(Color.WHITE);

    }//GEN-LAST:event_btn_navHome2MouseExited

    private void btn_navHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navHome2ActionPerformed
        new Customer_Homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navHome2ActionPerformed

    private void btn_navMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navMenu2MouseEntered
        if (!btn_navMenu2.getForeground().equals(new Color(255, 200, 120))) {
            btn_navMenu2.setForeground(new Color(255, 200, 120));
        }
        btn_navMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navMenu2MouseEntered

    private void btn_navMenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navMenu2MouseExited
        btn_navMenu2.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_navMenu2MouseExited

    private void btn_navMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navMenu2ActionPerformed
        new Customer_Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navMenu2ActionPerformed

    private void btn_navDine2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navDine2MouseEntered
        if (!btn_navDine2.getForeground().equals(new Color(255, 200, 120))) {
            btn_navDine2.setForeground(new Color(255, 200, 120));
        }
        btn_navDine2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navDine2MouseEntered

    private void btn_navDine2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navDine2MouseExited
        btn_navDine2.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_navDine2MouseExited

    private void btn_navDine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navDine2ActionPerformed
        new Customer_DineClub().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navDine2ActionPerformed

    private void btn_navReservations2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navReservations2MouseEntered
        if (!btn_navReservations2.getBackground().equals(new Color(217,180,95))) {
            btn_navReservations2.setBackground(new Color(217,180,95));
        }
        btn_navReservations2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navReservations2MouseEntered

    private void btn_navReservations2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navReservations2MouseExited
        btn_navReservations2.setBackground(new Color(185,153,79));
    }//GEN-LAST:event_btn_navReservations2MouseExited

    private void btn_navReservations2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navReservations2ActionPerformed
        new Customer_BookingHistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navReservations2ActionPerformed

    private void btn_navLogout2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navLogout2MouseEntered
        if (!btn_navLogout2.getBackground().equals(new Color(183,14,14))) {
            btn_navLogout2.setBackground(new Color(183,14,14));
        }
        btn_navLogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navLogout2MouseEntered

    private void btn_navLogout2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navLogout2MouseExited
        btn_navLogout2.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btn_navLogout2MouseExited

    private void btn_navLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navLogout2ActionPerformed

        int choice = JOptionPane.showConfirmDialog(null, "Log out of your account?", "Confirm Log Out", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            UserSession.loggedInEmail = null;
            new Customer_Login().setVisible(true);
            this.dispose();

        } else if (choice == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_btn_navLogout2ActionPerformed

    private void btn_navProf2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navProf2MouseEntered
        if (!btn_navProf2.getForeground().equals(new Color(255, 200, 120))) {
            btn_navProf2.setForeground(new Color(255, 200, 120));
        }
        btn_navProf2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_navProf2MouseEntered

    private void btn_navProf2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navProf2MouseExited
        btn_navProf2.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_navProf2MouseExited

    private void btn_navProf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_navProf2ActionPerformed
        new Customer_AcctProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_navProf2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer_Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutus_Label6;
    private javax.swing.JLabel Aboutus_label7;
    private javax.swing.JButton btn_navAbout2;
    private javax.swing.JButton btn_navDine2;
    private javax.swing.JButton btn_navHome2;
    private javax.swing.JButton btn_navLogout2;
    private javax.swing.JButton btn_navMenu2;
    private javax.swing.JButton btn_navProf2;
    private javax.swing.JButton btn_navReservations2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_innerMenu;
    private javax.swing.JScrollPane pnl_menuContainer;
    private javax.swing.JPanel pnl_nav3;
    // End of variables declaration//GEN-END:variables
public void switchPanel(javax.swing.JPanel panel) {
    pnlMain.removeAll();
    pnlMain.add(panel);
    pnlMain.repaint();
    pnlMain.revalidate();
}

private void fetchAndDisplayMenu(String category) {
    pnl_innerMenu.removeAll(); 

    Connect db = new Connect();
    db.DoConnect();

    String sql = "SELECT DISH_NAME, IMAGE_DATA FROM DBHOUSE.MENU_ITEMS WHERE CATEGORY = ?";
    
    try (PreparedStatement pst = db.con.prepareStatement(sql)) {
        pst.setString(1, category);
        
        try (ResultSet rs = pst.executeQuery()) {
            while (rs.next()) {
                String dishName = rs.getString("DISH_NAME");
                java.sql.Blob imageBlob = rs.getBlob("IMAGE_DATA");

                MenuItemPanel itemPanel = new MenuItemPanel(dishName, imageBlob);
                
                pnl_innerMenu.add(itemPanel);
            }
        }
        
    } catch (Exception e) {
        System.out.println("Error fetching menu: " + e.getMessage());
    }

    pnl_innerMenu.revalidate();
    pnl_innerMenu.repaint();
}
}
