/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author kyshgel
 */
public class Customer_Homepage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer_Homepage.class.getName());

    /**
     * Creates new form Customer_Homepage
     */
    public Customer_Homepage() {
        initComponents();
        menubar_navbar.setLayout(new java.awt.FlowLayout(
        java.awt.FlowLayout.LEFT, 20, 0));
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JMenuItem();
        img_homepage = new javax.swing.JLabel();
        panel_reservation = new java.awt.Panel();
        combobox_branch = new javax.swing.JComboBox<>();
        combobox_guest = new javax.swing.JComboBox<>();
        combobox_date = new javax.swing.JComboBox<>();
        combobox_time = new javax.swing.JComboBox<>();
        btn_reserve = new javax.swing.JButton();
        txt_desc = new javax.swing.JLabel();
        txt_buffetname = new javax.swing.JLabel();
        menubar_navbar = new javax.swing.JMenuBar();
        menu_profile = new javax.swing.JMenu();
        menu_reservation = new javax.swing.JMenu();
        menu_menulist = new javax.swing.JMenu();
        menu_branches = new javax.swing.JMenu();
        menu_about = new javax.swing.JMenu();

        navbar.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");
        setBackground(new java.awt.Color(241, 219, 201));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(225, 226, 225));

        img_homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ad4.png"))); // NOI18N
        img_homepage.setText("jLabel1");
        img_homepage.setMinimumSize(new java.awt.Dimension(900, 360));

        panel_reservation.setBackground(new java.awt.Color(117, 117, 117));

        combobox_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Branch", "Manila", "Alabang" }));

        combobox_guest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No. of Guests", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        combobox_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date" }));

        combobox_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time" }));

        btn_reserve.setText("Reserve");
        btn_reserve.addActionListener(this::btn_reserveActionPerformed);

        javax.swing.GroupLayout panel_reservationLayout = new javax.swing.GroupLayout(panel_reservation);
        panel_reservation.setLayout(panel_reservationLayout);
        panel_reservationLayout.setHorizontalGroup(
            panel_reservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reservationLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(combobox_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(combobox_guest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(combobox_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(combobox_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btn_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        panel_reservationLayout.setVerticalGroup(
            panel_reservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reservationLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_reservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_guest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        txt_desc.setText(" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam rutrum libero lectus, id cursus mauris sodales ac.");

        txt_buffetname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_buffetname.setText("(Name) Buffet");

        menubar_navbar.setMargin(new java.awt.Insets(5, 2, 2, 2));
        menubar_navbar.setPreferredSize(new java.awt.Dimension(344, 35));

        menu_profile.setText("Profile");
        menu_profile.setName(""); // NOI18N
        menubar_navbar.add(menu_profile);

        menu_reservation.setText("Reservation History");
        menubar_navbar.add(menu_reservation);

        menu_menulist.setText("Menu");
        menubar_navbar.add(menu_menulist);

        menu_branches.setText("Branches");
        menubar_navbar.add(menu_branches);

        menu_about.setText("About Us");
        menubar_navbar.add(menu_about);

        setJMenuBar(menubar_navbar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_buffetname, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(367, 367, 367))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(img_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_buffetname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reserveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer_Homepage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reserve;
    private javax.swing.JComboBox<String> combobox_branch;
    private javax.swing.JComboBox<String> combobox_date;
    private javax.swing.JComboBox<String> combobox_guest;
    private javax.swing.JComboBox<String> combobox_time;
    private javax.swing.JLabel img_homepage;
    private javax.swing.JMenu menu_about;
    private javax.swing.JMenu menu_branches;
    private javax.swing.JMenu menu_menulist;
    private javax.swing.JMenu menu_profile;
    private javax.swing.JMenu menu_reservation;
    private javax.swing.JMenuBar menubar_navbar;
    private javax.swing.JMenuItem navbar;
    private java.awt.Panel panel_reservation;
    private javax.swing.JLabel txt_buffetname;
    private javax.swing.JLabel txt_desc;
    // End of variables declaration//GEN-END:variables
}
