/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
/**
 *
 * @author lotte
 */
public class Customer_BookingConfirmation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer_BookingConfirmation.class.getName());
    
    private JFrame previousPaymentWindow;
    private String fName, lName, email, phone, mealType, paymentMethod, payerName, ewalletNum, cardNum, secNum, cardExp;
    private java.util.Date bookingDate;
    private int pax;
    
    
    public Customer_BookingConfirmation(JFrame previousPaymentWindow, String fName, String lName, String email, 
                                        String phone, java.util.Date bookingDate, String mealType, int pax, 
                                        String paymentMethod, String payerName, String ewalletNum, 
                                        String cardNum, String secNum, String cardExp) {
        
        this.previousPaymentWindow = previousPaymentWindow;
        this.fName = fName;
        this.lName = lName;
        this.email = email;
        this.phone = phone;
        this.bookingDate = bookingDate;
        this.mealType = mealType;
        this.pax = pax;
        this.paymentMethod = paymentMethod;
        this.payerName = payerName;
        this.ewalletNum = ewalletNum;
        this.cardNum = cardNum;
        this.secNum = secNum;
        this.cardExp = cardExp;
        
        initComponents();
        setLocationRelativeTo(null);
        
        displayBookingData();
    }
    
    private void displayBookingData() {
        lbl_name.setText(fName + " " + lName);
        lbl_email.setText(email);
        lbl_phonenum.setText(phone);
        
        if (bookingDate != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
            lbl_rsvdate.setText(sdf.format(bookingDate));
        }
        
        lbl_rsvtime.setText(mealType);
        lbl_pax.setText(String.valueOf(pax));
        
        lbl_paymentmethod.setText(paymentMethod != null ? paymentMethod : "");
        lbl_payername.setText(payerName != null ? payerName : "");
        lbl_ewallet_num.setText(ewalletNum != null ? ewalletNum : "");
        lbl_cardnum.setText(cardNum != null ? cardNum : "");
        lbl_secnum.setText(secNum != null ? secNum : "");
        lbl_cardexp.setText(cardExp != null ? cardExp : "");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_confirm = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_phonenum = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_rsvdate = new javax.swing.JLabel();
        lbl_rsvtime = new javax.swing.JLabel();
        lbl_pax = new javax.swing.JLabel();
        lbl_paymentmethod = new javax.swing.JLabel();
        lbl_payername = new javax.swing.JLabel();
        lbl_ewallet_num = new javax.swing.JLabel();
        lbl_cardnum = new javax.swing.JLabel();
        lbl_secnum = new javax.swing.JLabel();
        lbl_cardexp = new javax.swing.JLabel();
        btn_backpayment = new javax.swing.JButton();
        confirmation_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_confirm.setBackground(new java.awt.Color(23, 57, 86));
        btn_confirm.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_confirm.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirm.setText("Confirm");
        btn_confirm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_confirm.addActionListener(this::btn_confirmActionPerformed);
        getContentPane().add(btn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 80, 30));

        lbl_name.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 140, 20));

        lbl_phonenum.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 130, 20));

        lbl_email.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 216, 110, 20));

        lbl_rsvdate.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_rsvdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 100, 20));

        lbl_rsvtime.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_rsvtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 90, 20));

        lbl_pax.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_pax, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 40, 20));

        lbl_paymentmethod.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_paymentmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 346, 100, 20));

        lbl_payername.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_payername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 346, 100, 20));

        lbl_ewallet_num.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_ewallet_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 346, 130, 20));

        lbl_cardnum.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_cardnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 120, 20));
        getContentPane().add(lbl_secnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 130, 20));

        lbl_cardexp.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        getContentPane().add(lbl_cardexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 130, 20));

        btn_backpayment.setBackground(new java.awt.Color(255, 255, 255));
        btn_backpayment.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_backpayment.setForeground(new java.awt.Color(23, 57, 86));
        btn_backpayment.setText("<");
        btn_backpayment.setBorderPainted(false);
        btn_backpayment.addActionListener(this::btn_backpaymentActionPerformed);
        getContentPane().add(btn_backpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        confirmation_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CONFIRMATION.png"))); // NOI18N
        getContentPane().add(confirmation_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        Connect db = new Connect();
        db.DoConnect();

        if (db.con != null) {
            try (Connection con = db.con) {
                
                String vipId = null;
                String getVipSql = "SELECT VIP_ID FROM DBHOUSE.VIPACCOUNTS WHERE EMAIL = ?";
                try (PreparedStatement pstVip = con.prepareStatement(getVipSql)) {
                    pstVip.setString(1, UserSession.loggedInEmail);
                    try (ResultSet rsVip = pstVip.executeQuery()) {
                        if (rsVip.next()) {
                            vipId = rsVip.getString("VIP_ID");
                        }
                    }
                }
                
                if (vipId == null) {
                    JOptionPane.showMessageDialog(this, "Error: Could not verify user account. Please log in again.");
                    return;
                }

                String newOrId = getNextORId(con);

                String insertSql = "INSERT INTO DBHOUSE.ONLINERESERVATIONS (OR_ID, VIP_ID, D_DATE, D_TIME, PAX, REMARKS) VALUES (?, ?, ?, ?, ?, ?)";
                try (PreparedStatement pstInsert = con.prepareStatement(insertSql)) {
                    pstInsert.setString(1, newOrId);
                    pstInsert.setString(2, vipId);
                    pstInsert.setDate(3, new java.sql.Date(bookingDate.getTime())); 
                    pstInsert.setString(4, mealType); 
                    pstInsert.setInt(5, pax);
                    pstInsert.setString(6, "Going"); 

                    int rowsAffected = pstInsert.executeUpdate();
                    
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(this, "Your reservation is confirmed! Reference ID: " + newOrId, "Success", JOptionPane.INFORMATION_MESSAGE);
                        new Customer_Homepage().setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to save reservation. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "DB Error: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void btn_backpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backpaymentActionPerformed
        if (previousPaymentWindow != null) {
            previousPaymentWindow.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_backpaymentActionPerformed

    private String getNextORId(Connection con) {
        int nextNumber = 1; 

        String query = "SELECT MAX(CAST(SUBSTR(OR_ID, 3) AS INT)) FROM DBHOUSE.ONLINERESERVATIONS";
        
        try (PreparedStatement pst = con.prepareStatement(query);
             ResultSet rs = pst.executeQuery()) {

            if (rs.next()) {
                int maxId = rs.getInt(1);
                if (maxId > 0) {
                    nextNumber = maxId + 1;
                }
            }
        } catch (SQLException e) {
            System.out.println("ID Generation Note (First record likely): " + e.getMessage());
        }
        
        return String.format("OR%04d", nextNumber); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backpayment;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JLabel confirmation_bg;
    private javax.swing.JLabel lbl_cardexp;
    private javax.swing.JLabel lbl_cardnum;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_ewallet_num;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_pax;
    private javax.swing.JLabel lbl_payername;
    private javax.swing.JLabel lbl_paymentmethod;
    private javax.swing.JLabel lbl_phonenum;
    private javax.swing.JLabel lbl_rsvdate;
    private javax.swing.JLabel lbl_rsvtime;
    private javax.swing.JLabel lbl_secnum;
    // End of variables declaration//GEN-END:variables
}
