/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import gui.FrontDesk;
import javax.swing.Timer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
//hello
/**
 *
 * @author Ska
 */
public class Employee_Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Employee_Login.class.getName());

    /**
     * Creates new form Customer_Login
     */
    public Employee_Login() {
        initComponents();
        
        this.setResizable(true);
        getContentPane().setPreferredSize(new java.awt.Dimension(900, 580));
        pack();
        this.setResizable(false);
        
        setLocationRelativeTo(null);
        
        makeFlatButton(btn_emploginLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JLabel();
        lbl_welcomebck = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_emploginUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_emploginPass = new javax.swing.JPasswordField();
        btn_emploginLogin = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        chk_loginShowPass = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 580));
        getContentPane().setLayout(null);

        btn_back.setBackground(new java.awt.Color(204, 204, 204));
        btn_back.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_back.setText("<");
        btn_back.setToolTipText("");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(260, 120, 40, 36);

        lbl_welcomebck.setBackground(new java.awt.Color(47, 74, 91));
        lbl_welcomebck.setFont(new java.awt.Font("Century Gothic", 1, 40)); // NOI18N
        lbl_welcomebck.setForeground(new java.awt.Color(47, 74, 91));
        lbl_welcomebck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_welcomebck.setText("Employee Login");
        getContentPane().add(lbl_welcomebck);
        lbl_welcomebck.setBounds(290, 160, 309, 50);

        jLabel4.setBackground(new java.awt.Color(47, 74, 91));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 74, 91));
        jLabel4.setText("Username:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 220, 108, 19);

        txt_emploginUsername.setBackground(new java.awt.Color(229, 229, 229));
        txt_emploginUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_emploginUsername.setForeground(new java.awt.Color(47, 74, 91));
        txt_emploginUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txt_emploginUsername.addActionListener(this::txt_emploginUsernameActionPerformed);
        getContentPane().add(txt_emploginUsername);
        txt_emploginUsername.setBounds(310, 250, 275, 41);

        jLabel5.setBackground(new java.awt.Color(47, 74, 91));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(47, 74, 91));
        jLabel5.setText("Password:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 290, 108, 19);

        txt_emploginPass.setBackground(new java.awt.Color(229, 229, 229));
        txt_emploginPass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_emploginPass.setForeground(new java.awt.Color(47, 74, 91));
        txt_emploginPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 5, 10));
        getContentPane().add(txt_emploginPass);
        txt_emploginPass.setBounds(310, 320, 275, 40);

        btn_emploginLogin.setBackground(new java.awt.Color(47, 74, 91));
        btn_emploginLogin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_emploginLogin.setForeground(new java.awt.Color(238, 238, 238));
        btn_emploginLogin.setText("LOG-IN");
        btn_emploginLogin.setBorder(null);
        btn_emploginLogin.setMaximumSize(new java.awt.Dimension(293, 26));
        btn_emploginLogin.setMinimumSize(new java.awt.Dimension(293, 26));
        btn_emploginLogin.addActionListener(this::btn_emploginLoginActionPerformed);
        getContentPane().add(btn_emploginLogin);
        btn_emploginLogin.setBounds(390, 400, 108, 36);

        jLabel19.setBackground(new java.awt.Color(47, 74, 91));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(47, 74, 91));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Show Password");
        jLabel19.setToolTipText("");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(460, 370, 108, 16);

        chk_loginShowPass.setBackground(new java.awt.Color(153, 153, 153));
        chk_loginShowPass.addActionListener(this::chk_loginShowPassActionPerformed);
        getContentPane().add(chk_loginShowPass);
        chk_loginShowPass.setBounds(570, 370, 19, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employeelogin.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_loginShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_loginShowPassActionPerformed
        if (chk_loginShowPass.isSelected()) {
            txt_emploginPass.setEchoChar((char)0);
        } else {
            txt_emploginPass.setEchoChar('*');
        }
    }//GEN-LAST:event_chk_loginShowPassActionPerformed

    private void btn_emploginLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emploginLoginActionPerformed
        String username = txt_emploginUsername.getText().trim();
        String password = new String(txt_emploginPass.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both Username and Password.");
            return;
        }

        // ADMIN ACC
        if (username.equals("admin") && password.equals("admin")) {
            new Admin().setVisible(true);
            this.dispose();
            return;
        }

        Connect db = new Connect();
        db.DoConnect();

        if (db.con != null) {

            try (Connection con = db.con;
                PreparedStatement pst = con.prepareStatement("SELECT * FROM DBHOUSE.EMPACCOUNTS WHERE USERNAME = ? AND PASS = ?")) {

                pst.setString(1, username);
                pst.setString(2, password);

                try (ResultSet rs = pst.executeQuery()) {
                    if (rs.next()) {
                        String accType = rs.getString("ACC_TYPE");
                        String fullName = rs.getString("F_NAME") + " " + rs.getString("L_NAME");

                        JOptionPane.showMessageDialog(this, "Welcome, " + fullName + ", " + accType + ".", "Login Successful", JOptionPane.PLAIN_MESSAGE);

                       switch (accType.toLowerCase()) {
                            case "admin":
                            new Admin().setVisible(true);
                            break;

                            case "gen. manager":
                            new GenManager().setVisible(true);
                            break;

                            case "manager":
                            new Manager().setVisible(true);
                            break;

                            case "front desk":
                            new FrontDesk(fullName).setVisible(true); 
                            break;

                            default:
                            JOptionPane.showMessageDialog(this, "Access Denied");
                            return;
                        }

                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Username or Password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "DB Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_emploginLoginActionPerformed

    private void txt_emploginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emploginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emploginUsernameActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        new Customer_Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked
    
   
    /**
     * @param args the command line arguments
     */
    
    private void makeFlatButton(javax.swing.JButton btn) {
    btn.setFocusPainted(false);
    btn.setBorder(null);
    btn.setContentAreaFilled(false);
    btn.setOpaque(true);
    btn.setBackground(new java.awt.Color(47, 74, 91));
    btn.setForeground(java.awt.Color.WHITE);
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    btn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btn.setBackground(new java.awt.Color(60, 90, 110));
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            btn.setBackground(new java.awt.Color(47, 74, 91));
        }
    });
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Employee_Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JButton btn_emploginLogin;
    private javax.swing.JCheckBox chk_loginShowPass;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_welcomebck;
    private javax.swing.JPasswordField txt_emploginPass;
    private javax.swing.JTextField txt_emploginUsername;
    // End of variables declaration//GEN-END:variables
}
