/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kyshgel
 */
public class FrontDesk_Today extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrontDesk_Today.class.getName());

    /**
     * Creates new form FrontDesk_Homepage
     */
    public FrontDesk_Today() {
        initComponents();
        this.setLocationRelativeTo(null);
        TableRowSorter sorter = new TableRowSorter(tbl_today.getModel());
        tbl_today.setRowSorter(sorter);
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        tbl_today.getColumnModel().getColumn(0).setCellRenderer(center);
        tbl_today.getColumnModel().getColumn(1).setCellRenderer(center);
        tbl_today.getColumnModel().getColumn(2).setCellRenderer(center);
        tbl_today.getColumnModel().getColumn(3).setCellRenderer(center);
        tbl_today.getColumnModel().getColumn(4).setCellRenderer(center);
        
        int total = 0;

        for (int i = 0; i < tbl_today.getRowCount(); i++) {
            Object value; // column 0
            value = tbl_today.getValueAt(i, 0);

        if (value != null && !value.toString().trim().equals("")) {
            total++;
    }
}

        txt_total.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_today = new javax.swing.JButton();
        btn_upcoming = new javax.swing.JButton();
        btn_history = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        search_today = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_today = new javax.swing.JTable();
        bg_today = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(55, 77, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imresizer-invertedlogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 70));

        btn_today.setBackground(new java.awt.Color(55, 77, 94));
        btn_today.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_today.setForeground(new java.awt.Color(255, 255, 255));
        btn_today.setText("TODAY");
        btn_today.setBorder(null);
        btn_today.setContentAreaFilled(false);
        btn_today.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today.setFocusPainted(false);
        btn_today.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_todayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_todayMouseExited(evt);
            }
        });
        jPanel1.add(btn_today, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, -1));

        btn_upcoming.setBackground(new java.awt.Color(55, 77, 94));
        btn_upcoming.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_upcoming.setForeground(new java.awt.Color(255, 255, 255));
        btn_upcoming.setText("UPCOMING");
        btn_upcoming.setBorder(null);
        btn_upcoming.setContentAreaFilled(false);
        btn_upcoming.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_upcoming.setFocusPainted(false);
        btn_upcoming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_upcomingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_upcomingMouseExited(evt);
            }
        });
        btn_upcoming.addActionListener(this::btn_upcomingActionPerformed);
        jPanel1.add(btn_upcoming, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 30));

        btn_history.setBackground(new java.awt.Color(55, 77, 94));
        btn_history.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_history.setForeground(new java.awt.Color(255, 255, 255));
        btn_history.setText("HISTORY");
        btn_history.setBorder(null);
        btn_history.setContentAreaFilled(false);
        btn_history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_history.setFocusPainted(false);
        btn_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_historyMouseExited(evt);
            }
        });
        btn_history.addActionListener(this::btn_historyActionPerformed);
        jPanel1.add(btn_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 30));

        btn_logout.setBackground(new java.awt.Color(153, 0, 0));
        btn_logout.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("LOG OUT");
        btn_logout.setBorder(null);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 521, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 580));

        jPanel2.setBackground(new java.awt.Color(55, 91, 115));
        jPanel2.setMaximumSize(new java.awt.Dimension(681, 115));
        jPanel2.setPreferredSize(new java.awt.Dimension(681, 115));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FRONT DESK DASHBOARD");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(55, 91, 115));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("                         Name");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(55, 91, 115));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 740, -1));

        jPanel3.setForeground(new java.awt.Color(202, 199, 199));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 90, 90));
        jLabel4.setText("TODAY");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("TOTAL:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 70, 40));

        txt_total.setBackground(new java.awt.Color(237, 236, 234));
        txt_total.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt_total.setForeground(new java.awt.Color(102, 102, 102));
        txt_total.setBorder(null);
        jPanel3.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Search:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 50, 40));

        search_today.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_todayKeyReleased(evt);
            }
        });
        jPanel3.add(search_today, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 170, -1));

        jScrollPane1.setForeground(new java.awt.Color(55, 77, 94));

        tbl_today.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbl_today.setForeground(new java.awt.Color(51, 51, 51));
        tbl_today.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Juan Dela Cruz", "09357873489",  new Integer(4), "Lunch"},
                { new Integer(2), "Maria Santos", "09174532356",  new Integer(3), "Lunch"},
                { new Integer(3), "Louise Lopez", "09876541453",  new Integer(2), "Dinner"},
                { new Integer(4), "Rhian Espinosa", "09258653421",  new Integer(6), "Dinner"},
                { new Integer(5), "Justine Dizon", "09987823421",  new Integer(7), "Lunch"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TABLE NO.", "CUSTOMER NAME", "CONTACT", "PAX", "TIME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_today.setOpaque(false);
        jScrollPane1.setViewportView(tbl_today);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 700, 330));

        bg_today.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bgfd.jpg"))); // NOI18N
        bg_today.setText("Today");
        jPanel3.add(bg_today, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 740, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_todayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_todayMouseEntered
    btn_today.setForeground(new Color(255,200,120));
    btn_today.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_btn_todayMouseEntered

    private void btn_upcomingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_upcomingMouseEntered
    btn_upcoming.setForeground(new Color(255,200,120));
    btn_upcoming.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_btn_upcomingMouseEntered

    private void btn_historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historyMouseEntered
    btn_history.setForeground(new Color(255,200,120));
    btn_history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_btn_historyMouseEntered

    private void btn_todayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_todayMouseExited
    btn_today.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_todayMouseExited

    private void btn_upcomingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_upcomingMouseExited
    btn_upcoming.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_upcomingMouseExited

    private void btn_historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historyMouseExited
    btn_history.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_historyMouseExited

    private void search_todayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_todayKeyReleased
    String text = search_today.getText();
    TableRowSorter sorter = (TableRowSorter) tbl_today.getRowSorter();
    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));      // TODO add your handling code here:
    }//GEN-LAST:event_search_todayKeyReleased

    private void btn_upcomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upcomingActionPerformed
    FrontDesk_Upcoming upcoming = new FrontDesk_Upcoming();
    upcoming.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_upcomingActionPerformed

    private void btn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historyActionPerformed
    FrontDesk_History history = new FrontDesk_History();
    history.setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_btn_historyActionPerformed
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrontDesk_Today().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_today;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_today;
    private javax.swing.JButton btn_upcoming;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField search_today;
    private javax.swing.JTable tbl_today;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}

