/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author lotte
 */
public class Payment_Window_Method extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Payment_Window_Method.class.getName());

    /**
     * Creates new form Payment_Window_Method
     */
    public Payment_Window_Method() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card_checkb_payment = new javax.swing.JCheckBox();
        gcash_checkb_payment = new javax.swing.JCheckBox();
        fn_txt_payment = new javax.swing.JTextField();
        ln_txt_payment = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        secnum_txt_payment = new javax.swing.JTextField();
        cardexp_txt_payment = new javax.swing.JTextField();
        confirm_txt_payment = new javax.swing.JButton();
        payment_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card_checkb_payment.setIconTextGap(0);
        getContentPane().add(card_checkb_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 50, 40));

        gcash_checkb_payment.setIconTextGap(0);
        getContentPane().add(gcash_checkb_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 50, 40));

        fn_txt_payment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(fn_txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, 30));

        ln_txt_payment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(ln_txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 170, 30));

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 170, 30));

        secnum_txt_payment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(secnum_txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 170, 30));

        cardexp_txt_payment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(cardexp_txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 170, 30));

        confirm_txt_payment.setBackground(new java.awt.Color(185, 153, 79));
        confirm_txt_payment.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        confirm_txt_payment.setText("Confirm Reservation");
        confirm_txt_payment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(confirm_txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 150, 30));

        payment_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/PAYMENT.png"))); // NOI18N
        getContentPane().add(payment_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Payment_Window_Method().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox card_checkb_payment;
    private javax.swing.JTextField cardexp_txt_payment;
    private javax.swing.JButton confirm_txt_payment;
    private javax.swing.JTextField fn_txt_payment;
    private javax.swing.JCheckBox gcash_checkb_payment;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField ln_txt_payment;
    private javax.swing.JLabel payment_bg;
    private javax.swing.JTextField secnum_txt_payment;
    // End of variables declaration//GEN-END:variables
}
