/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package img;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author Ska
 */
public class MenuItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuItemPanel
     */
    
    
 public MenuItemPanel(String dishName, java.sql.Blob imageBlob) {
        initComponents();
        lbl_dishName.setText(dishName);
        
        try {
            if (imageBlob != null) {
                byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
                ImageIcon icon = new ImageIcon(imageBytes);
                Image img = icon.getImage();
                
                int originalWidth = img.getWidth(null);
                int originalHeight = img.getHeight(null);
                
                int boundWidth = 150;
                int boundHeight = 150;
                
                double scaleFactor = Math.min((double) boundWidth / originalWidth, (double) boundHeight / originalHeight);
                
                int newWidth = (int) (originalWidth * scaleFactor);
                int newHeight = (int) (originalHeight * scaleFactor);
                
                Image scaled = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
                lbl_dishImage.setIcon(new ImageIcon(scaled));
                
                lbl_dishImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbl_dishImage.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
                lbl_dishImage.setText(""); 
            }
        } catch (Exception e) {
            lbl_dishImage.setText("No Image");
        }
    }
    public MenuItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_dishImage = new javax.swing.JLabel();
        lbl_dishName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(226, 226, 226));
        setToolTipText("");

        lbl_dishImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lbl_dishName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_dishName.setForeground(new java.awt.Color(55, 77, 94));
        lbl_dishName.setText("Dish Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_dishName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dishImage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_dishImage, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_dishName)
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_dishImage;
    private javax.swing.JLabel lbl_dishName;
    // End of variables declaration//GEN-END:variables
}
