/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package img;
import java.awt.Image;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Ska
 */
public class PromoItemPanel extends javax.swing.JPanel {

    private Image originalImage = null;
    
    
public PromoItemPanel(String promoName, java.sql.Blob imageBlob) {
        initComponents();
        
        try {
            if (imageBlob != null) {
                byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
                ImageIcon icon = new ImageIcon(imageBytes);
                Image img = icon.getImage();
                
                originalImage = img; 
                
                int originalWidth = img.getWidth(null);
                int originalHeight = img.getHeight(null);
                
                int boundWidth = 265;
                int boundHeight = 340;
                
                double scaleFactor = Math.min((double) boundWidth / originalWidth, (double) boundHeight / originalHeight);
                
                int newWidth = (int) (originalWidth * scaleFactor);
                int newHeight = (int) (originalHeight * scaleFactor);
                
                Image scaled = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
                lbl_promoImage.setIcon(new ImageIcon(scaled));
                
                lbl_promoImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbl_promoImage.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
                lbl_promoImage.setText(""); 
                
                lbl_promoImage.setCursor(new Cursor(Cursor.HAND_CURSOR));
                
                lbl_promoImage.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        showEnlargedImage(promoName); 
                    }
                });
            }
        } catch (Exception e) {
            lbl_promoImage.setText("No Image");
        }
    }
    public PromoItemPanel() {
        initComponents();
    }
    
    private void showEnlargedImage(String promoTitle) {
        if (originalImage == null) return;
        
        int origW = originalImage.getWidth(null);
        int origH = originalImage.getHeight(null);
        
        int maxW = 700;
        int maxH = 600;
        
        Image displayImage = originalImage;
        
        if (origW > maxW || origH > maxH) {
            double scale = Math.min((double) maxW / origW, (double) maxH / origH);
            int newW = (int) (origW * scale);
            int newH = (int) (origH * scale);
            displayImage = originalImage.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
        }
        
        JLabel imgLabel = new JLabel(new ImageIcon(displayImage));
        JOptionPane.showMessageDialog(null, imgLabel, promoTitle, JOptionPane.PLAIN_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_promoImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(226, 226, 226));
        setToolTipText("");

        lbl_promoImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_promoImage, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_promoImage, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_promoImage;
    // End of variables declaration//GEN-END:variables
}
