/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ONIN
 */
public class Res_History2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Res_History2.class.getName());

    /**
     * Creates new form Res_History2
     */
    public Res_History2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Aboutus_Label2 = new javax.swing.JLabel();
        Aboutus_label3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_today5 = new javax.swing.JButton();
        btn_today6 = new javax.swing.JButton();
        btn_today7 = new javax.swing.JButton();
        btn_today8 = new javax.swing.JButton();
        btn_logout2 = new javax.swing.JButton();
        Aboutus_Label3 = new javax.swing.JLabel();
        Aboutus_label4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_today9 = new javax.swing.JButton();
        btn_today10 = new javax.swing.JButton();
        btn_today11 = new javax.swing.JButton();
        btn_today12 = new javax.swing.JButton();
        btn_logout3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnl_header = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_history = new javax.swing.JTable();
        jLabel_upc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(900, 580));
        setSize(new java.awt.Dimension(900, 580));

        jPanel4.setBackground(new java.awt.Color(57, 77, 94));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aboutus_Label2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        Aboutus_Label2.setForeground(new java.awt.Color(153, 153, 153));
        Aboutus_Label2.setText("© 2026 The House Of 7 Buffet.");
        jPanel4.add(Aboutus_Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        Aboutus_label3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        Aboutus_label3.setForeground(new java.awt.Color(153, 153, 153));
        Aboutus_label3.setText("All Rights Reserved.");
        jPanel4.add(Aboutus_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 80));

        btn_today5.setBackground(new java.awt.Color(55, 77, 94));
        btn_today5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_today5.setForeground(new java.awt.Color(255, 255, 255));
        btn_today5.setText("About Us");
        btn_today5.setBorder(null);
        btn_today5.setContentAreaFilled(false);
        btn_today5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today5.setFocusPainted(false);
        btn_today5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_today5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_today5MouseExited(evt);
            }
        });
        btn_today5.addActionListener(this::btn_today5ActionPerformed);
        jPanel4.add(btn_today5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        btn_today6.setBackground(new java.awt.Color(55, 77, 94));
        btn_today6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_today6.setForeground(new java.awt.Color(255, 255, 255));
        btn_today6.setText("Profile");
        btn_today6.setBorder(null);
        btn_today6.setContentAreaFilled(false);
        btn_today6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today6.setFocusPainted(false);
        btn_today6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_today6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_today6MouseExited(evt);
            }
        });
        btn_today6.addActionListener(this::btn_today6ActionPerformed);
        jPanel4.add(btn_today6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        btn_today7.setBackground(new java.awt.Color(55, 77, 94));
        btn_today7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_today7.setForeground(new java.awt.Color(255, 255, 255));
        btn_today7.setText("Menu & Specials");
        btn_today7.setBorder(null);
        btn_today7.setContentAreaFilled(false);
        btn_today7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today7.setFocusPainted(false);
        btn_today7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_today7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_today7MouseExited(evt);
            }
        });
        btn_today7.addActionListener(this::btn_today7ActionPerformed);
        jPanel4.add(btn_today7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));

        btn_today8.setBackground(new java.awt.Color(55, 77, 94));
        btn_today8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_today8.setForeground(new java.awt.Color(255, 255, 255));
        btn_today8.setText("Dine Club");
        btn_today8.setBorder(null);
        btn_today8.setContentAreaFilled(false);
        btn_today8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today8.setFocusPainted(false);
        btn_today8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_today8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_today8MouseExited(evt);
            }
        });
        btn_today8.addActionListener(this::btn_today8ActionPerformed);
        jPanel4.add(btn_today8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 30));

        btn_logout2.setBackground(new java.awt.Color(185, 153, 79));
        btn_logout2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_logout2.setForeground(new java.awt.Color(57, 77, 94));
        btn_logout2.setText("MY RESERVATIONS");
        btn_logout2.setBorder(null);
        btn_logout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout2.addActionListener(this::btn_logout2ActionPerformed);
        jPanel4.add(btn_logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 30));

        Aboutus_Label3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        Aboutus_Label3.setForeground(new java.awt.Color(153, 153, 153));
        Aboutus_Label3.setText("© 2026 The House Of 7 Buffet.");
        jPanel4.add(Aboutus_Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        Aboutus_label4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        Aboutus_label4.setForeground(new java.awt.Color(153, 153, 153));
        Aboutus_label4.setText("All Rights Reserved.");
        jPanel4.add(Aboutus_label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 80));

        btn_today9.setBackground(new java.awt.Color(55, 77, 94));
        btn_today9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_today9.setForeground(new java.awt.Color(255, 255, 255));
        btn_today9.setText("About Us");
        btn_today9.setBorder(null);
        btn_today9.setContentAreaFilled(false);
        btn_today9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today9.setFocusPainted(false);
        btn_today9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_today9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_today9MouseExited(evt);
            }
        });
        btn_today9.addActionListener(this::btn_today9ActionPerformed);
        jPanel4.add(btn_today9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        btn_today10.setBackground(new java.awt.Color(55, 77, 94));
        btn_today10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_today10.setForeground(new java.awt.Color(255, 255, 255));
        btn_today10.setText("Profile");
        btn_today10.setBorder(null);
        btn_today10.setContentAreaFilled(false);
        btn_today10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today10.setFocusPainted(false);
        btn_today10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_today10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_today10MouseExited(evt);
            }
        });
        btn_today10.addActionListener(this::btn_today10ActionPerformed);
        jPanel4.add(btn_today10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        btn_today11.setBackground(new java.awt.Color(55, 77, 94));
        btn_today11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_today11.setForeground(new java.awt.Color(255, 255, 255));
        btn_today11.setText("Menu & Specials");
        btn_today11.setBorder(null);
        btn_today11.setContentAreaFilled(false);
        btn_today11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today11.setFocusPainted(false);
        btn_today11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_today11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_today11MouseExited(evt);
            }
        });
        btn_today11.addActionListener(this::btn_today11ActionPerformed);
        jPanel4.add(btn_today11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));

        btn_today12.setBackground(new java.awt.Color(55, 77, 94));
        btn_today12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_today12.setForeground(new java.awt.Color(255, 255, 255));
        btn_today12.setText("Dine Club");
        btn_today12.setBorder(null);
        btn_today12.setContentAreaFilled(false);
        btn_today12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_today12.setFocusPainted(false);
        btn_today12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_today12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_today12MouseExited(evt);
            }
        });
        btn_today12.addActionListener(this::btn_today12ActionPerformed);
        jPanel4.add(btn_today12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 30));

        btn_logout3.setBackground(new java.awt.Color(185, 153, 79));
        btn_logout3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_logout3.setForeground(new java.awt.Color(57, 77, 94));
        btn_logout3.setText("MY RESERVATIONS");
        btn_logout3.setBorder(null);
        btn_logout3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout3.addActionListener(this::btn_logout3ActionPerformed);
        jPanel4.add(btn_logout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ONIN\\Downloads\\646453937_1598106948556555_6145942253891469452_n.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 99, -1));

        pnl_header.setBackground(new java.awt.Color(55, 91, 115));

        lbl_username.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_username.setText("Dela Cruz, Juan");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MY RESERVATIONS");

        javax.swing.GroupLayout pnl_headerLayout = new javax.swing.GroupLayout(pnl_header);
        pnl_header.setLayout(pnl_headerLayout);
        pnl_headerLayout.setHorizontalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_headerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        pnl_headerLayout.setVerticalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_headerLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_headerLayout.createSequentialGroup()
                        .addComponent(lbl_username)
                        .addGap(28, 28, 28))))
        );

        jScrollPane2.setForeground(new java.awt.Color(55, 77, 94));

        tbl_history.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tbl_history.setForeground(new java.awt.Color(55, 77, 94));
        tbl_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"03-26-26", "Lunch", "1"},
                {"03-01-26", "Lunch", "3"}
            },
            new String [] {
                "DATE", "TIME", "PAX"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_history.setOpaque(false);
        jScrollPane2.setViewportView(tbl_history);
        if (tbl_history.getColumnModel().getColumnCount() > 0) {
            tbl_history.getColumnModel().getColumn(0).setResizable(false);
            tbl_history.getColumnModel().getColumn(1).setResizable(false);
            tbl_history.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel_upc.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel_upc.setForeground(new java.awt.Color(55, 77, 94));
        jLabel_upc.setText("UPCOMING");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(pnl_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jLabel_upc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel_upc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logout2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logout2ActionPerformed

    private void btn_today8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today8ActionPerformed

    private void btn_today8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today8MouseExited

    private void btn_today8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today8MouseEntered

    private void btn_today7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today7ActionPerformed

    private void btn_today7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today7MouseExited

    private void btn_today7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today7MouseEntered

    private void btn_today6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today6ActionPerformed

    private void btn_today6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today6MouseExited

    private void btn_today6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today6MouseEntered

    private void btn_today5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today5ActionPerformed

    private void btn_today5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today5MouseExited

    private void btn_today5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today5MouseEntered

    private void btn_today9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today9MouseEntered

    private void btn_today9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today9MouseExited

    private void btn_today9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today9ActionPerformed

    private void btn_today10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today10MouseEntered

    private void btn_today10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today10MouseExited

    private void btn_today10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today10ActionPerformed

    private void btn_today11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today11MouseEntered

    private void btn_today11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today11MouseExited

    private void btn_today11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today11ActionPerformed

    private void btn_today12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today12MouseEntered

    private void btn_today12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_today12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today12MouseExited

    private void btn_today12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_today12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_today12ActionPerformed

    private void btn_logout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logout3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logout3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Res_History2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutus_Label2;
    private javax.swing.JLabel Aboutus_Label3;
    private javax.swing.JLabel Aboutus_label3;
    private javax.swing.JLabel Aboutus_label4;
    private javax.swing.JButton btn_logout2;
    private javax.swing.JButton btn_logout3;
    private javax.swing.JButton btn_today10;
    private javax.swing.JButton btn_today11;
    private javax.swing.JButton btn_today12;
    private javax.swing.JButton btn_today5;
    private javax.swing.JButton btn_today6;
    private javax.swing.JButton btn_today7;
    private javax.swing.JButton btn_today8;
    private javax.swing.JButton btn_today9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_upc;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JTable tbl_history;
    // End of variables declaration//GEN-END:variables
}
